import { createClient } from "jsr:@supabase/supabase-js@2";

const VERSION = "Stream Bandit TCG private alpha API v0.2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
const env=(n:string)=>Deno.env.get(n)||"";
function firstKey(raw:string){if(!raw)return"";try{const x=JSON.parse(raw);if(typeof x==="string")return x;const vals=Array.isArray(x)?x:Object.values(x||{});for(const it of vals){if(typeof it==="string")return it;if(it&&typeof it==="object"){const o=it as Record<string,unknown>;for(const k of ["value","key","secret","api_key"])if(typeof o[k]==="string")return o[k] as string}}}catch{return raw}return""}
const need=(n:string,v:string)=>{if(!v)throw new Error(`Missing ${n}`);return v};
function secureInt(max:number){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=secureInt(i+1);[x[i],x[j]]=[x[j],x[i]]}return x}
type Inst={uid:string,card_id:string};
type SnapCard={card_id:string,quantity:number,name:string,element:string,card_family:string,definition:Record<string,unknown>};
function expandDeck(cards:SnapCard[]):Inst[]{const out:Inst[]=[];for(const c of cards||[])for(let i=0;i<Number(c.quantity||0);i++)out.push({uid:crypto.randomUUID(),card_id:c.card_id});return shuffle(out)}
function recipe(meta:Record<string,any>|undefined){return String(meta?.definition?.recipe_type||meta?.definition?.recipeType||"")}
function starterLegal(meta:Record<string,any>|undefined){const r=recipe(meta);return r==="Creature — Baby"||r==="Creature — Standalone"||r==="Creature — Mythic"}
function opening(deck0:Inst[],meta:Record<string,any>){let deck=[...deck0],mulligans=0;for(let guard=0;guard<100;guard++){const hand=deck.splice(0,7);if(hand.some(i=>starterLegal(meta[i.card_id])))return{deck,hand,mulligans};mulligans++;deck=shuffle([...deck,...hand])}throw new Error("opening_hand_mulligan_guard")}
function creatureFrom(inst:Inst){return{stack:[inst],essence:[],relic:null,damage:0,shield:0,condition:null,flags:{}}}
function publicField(p:any){return{vanguard:p.vanguard,reserve:p.reserve,discard_count:p.discard.length,void_count:p.void.length,rewards_count:p.rewards.length,deck_count:p.deck.length,hand_count:p.hand.length}}
function makeView(s:any,viewerSeat:number,revision:number){const own=s.players[String(viewerSeat)],opp=s.players[String(viewerSeat===1?2:1)];return{version:s.version,match_id:s.match_id,revision,phase:s.phase,toss_winner_seat:s.toss_winner_seat,first_player_seat:s.first_player_seat,setup_turn_seat:s.setup_turn_seat,active_seat:s.active_seat,turn_seq:s.turn_seq,personal_turns:s.personal_turns,setup_ready:s.setup_ready,realm:s.realm,log:s.log.slice(-12),you:{seat:viewerSeat,user_id:own.user_id,hand:own.hand,deck_count:own.deck.length,rewards_count:own.rewards.length,vanguard:own.vanguard,reserve:own.reserve,discard:own.discard,void_count:own.void.length,mulligans:own.mulligans,deck_meta:own.deck_meta},opponent:{seat:opp.seat,user_id:opp.user_id,...publicField(opp),mulligans:opp.mulligans,deck_meta:{name:opp.deck_meta.name,primary_element:opp.deck_meta.primary_element}},card_index:s.card_index}}
function views(s:any,revision:number){return{p1:makeView(s,1,revision),p2:makeView(s,2,revision)}}

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
 if(req.method!=="POST")return json({ok:false,version:VERSION,error:"POST only"},405);
 try{
  const authHeader=req.headers.get("Authorization")||"";if(!authHeader.startsWith("Bearer "))return json({ok:false,version:VERSION,error:"signed_in_user_required"},401);
  const url=need("SUPABASE_URL",env("SUPABASE_URL"));const publishable=need("publishable key",env("SUPABASE_ANON_KEY")||firstKey(env("SUPABASE_PUBLISHABLE_KEYS")));const service=need("service role key",env("SUPABASE_SERVICE_ROLE_KEY")||firstKey(env("SUPABASE_SECRET_KEYS")));
  const user=createClient(url,publishable,{global:{headers:{Authorization:authHeader}},auth:{autoRefreshToken:false,persistSession:false}});const admin=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
  const {data:ud,error:ue}=await user.auth.getUser();const userId=ud?.user?.id||"";if(ue||!userId)return json({ok:false,version:VERSION,error:"invalid_user_token"},401);
  let body:Record<string,unknown>={};try{body=await req.json()}catch{return json({ok:false,version:VERSION,error:"invalid_json"},400)}const action=String(body.action||"").trim();
  const rpc=async(fn:string,args:Record<string,unknown>)=>{const {data,error}=await admin.rpc(fn,args);if(error)throw new Error(`${fn}: ${error.message}`);return data};
  const getBundle=async(matchId:string)=>{const [{data:st,error:se},{data:ps,error:pe}]=await Promise.all([admin.from("tcg_match_state_private").select("revision,canonical_state").eq("match_id",matchId).maybeSingle(),admin.from("tcg_match_players").select("user_id,seat,deck_snapshot").eq("match_id",matchId).order("seat")]);if(se)throw se;if(pe)throw pe;if(!st||!ps||ps.length!==2)throw new Error("match_bundle_missing");return{revision:Number(st.revision),state:st.canonical_state as any,players:ps as any[]}};
  const initialize=async(roomId:string)=>{const prep:any=await rpc("tcg_server_prepare_match",{p_room_id:roomId});if(!prep?.ok)return prep;const matchId=String(prep.match_id);const existing=await admin.from("tcg_match_state_private").select("match_id").eq("match_id",matchId).maybeSingle();if(existing.data)return{ok:true,already_initialized:true,match_id:matchId};const players=[...(prep.players||[])].sort((a:any,b:any)=>a.seat-b.seat);const cardIndex:Record<string,any>={};const built:any={};for(const p of players){const snap=p.deck_snapshot;for(const c of snap.cards||[])cardIndex[c.card_id]=c;const full=expandDeck(snap.cards||[]);if(full.length!==60)throw new Error(`deck_snapshot_not_60_seat_${p.seat}`);const op=opening(full,cardIndex);built[String(p.seat)]={user_id:p.user_id,seat:p.seat,deck_meta:{deck_id:snap.deck_id,name:snap.name,primary_element:snap.primary_element,secondary_element:snap.secondary_element,rules_version:snap.rules_version},deck:op.deck,hand:op.hand,rewards:[],discard:[],void:[],vanguard:null,reserve:[null,null,null,null],mulligans:op.mulligans}}
   const toss=secureInt(2)+1;const state={version:"set-one-v0.6.1",match_id:matchId,room_id:roomId,phase:"opening_choice",toss_winner_seat:toss,first_player_seat:null,setup_turn_seat:null,active_seat:null,turn_seq:0,personal_turns:{"1":0,"2":0},setup_ready:{"1":false,"2":false},realm:null,players:built,card_index:cardIndex,log:[`Match created. Seat ${toss} won the opening toss.`]};const v=views(state,0);const installed:any=await rpc("tcg_server_install_initial_state",{p_match_id:matchId,p_canonical_state:state,p_player_one_id:built["1"].user_id,p_player_one_view:v.p1,p_player_two_id:built["2"].user_id,p_player_two_view:v.p2});return{...installed,toss_winner_seat:toss}}
  const commit=async(bundle:any,actor:string,nonce:string,commandType:string,newState:any,eventType:string,payload:any)=>{const next=bundle.revision+1;const v=views(newState,next);return await rpc("tcg_server_commit_state",{p_match_id:newState.match_id,p_actor_user_id:actor,p_client_nonce:nonce,p_expected_revision:bundle.revision,p_command_type:commandType,p_new_state:newState,p_player_one_id:newState.players["1"].user_id,p_player_one_view:v.p1,p_player_two_id:newState.players["2"].user_id,p_player_two_view:v.p2,p_event_type:eventType,p_public_payload:payload||{}})};

  if(action==="ping")return json({ok:true,version:VERSION,user_id:userId});
  if(action==="choose_starter"){const id=String(body.starter_id||"").trim();if(!id)return json({ok:false,error:"starter_id_required",version:VERSION},400);return json({version:VERSION,result:await rpc("tcg_server_grant_starter",{p_user_id:userId,p_starter_id:id})})}
  if(action==="create_room"){const d=String(body.deck_id||"").trim();if(!d)return json({ok:false,error:"deck_id_required",version:VERSION},400);return json({version:VERSION,result:await rpc("tcg_server_create_room",{p_user_id:userId,p_deck_id:d})})}
  if(action==="join_room"){const code=String(body.join_code||"").trim().toUpperCase(),d=String(body.deck_id||"").trim();if(!code||!d)return json({ok:false,error:"join_code_and_deck_id_required",version:VERSION},400);return json({version:VERSION,result:await rpc("tcg_server_join_room",{p_user_id:userId,p_join_code:code,p_deck_id:d})})}
  if(action==="set_ready"){const room=String(body.room_id||"").trim(),d=String(body.deck_id||"").trim();if(!room||!d)return json({ok:false,error:"room_id_and_deck_id_required",version:VERSION},400);const r:any=await rpc("tcg_server_set_room_ready",{p_user_id:userId,p_room_id:room,p_deck_id:d,p_ready:body.ready!==false});let match=null;if(r?.all_ready)match=await initialize(room);return json({version:VERSION,result:r,match})}
  if(action==="room_snapshot"){const room=String(body.room_id||"").trim();return json({version:VERSION,result:await rpc("tcg_server_room_snapshot",{p_user_id:userId,p_room_id:room})})}
  if(action==="match_view"){const match=String(body.match_id||"").trim();const {data,error}=await user.from("tcg_match_views").select("revision,view_state,updated_at").eq("match_id",match).eq("user_id",userId).maybeSingle();if(error)return json({ok:false,version:VERSION,error:error.message},400);return json({ok:true,version:VERSION,view:data})}

  if(["opening_choice","setup_place","setup_return","setup_ready","end_turn"].includes(action)){
   const matchId=String(body.match_id||"").trim(),nonce=String(body.client_nonce||"").trim();const expected=Number(body.expected_revision);if(!matchId||!nonce||!Number.isInteger(expected)||expected<0)return json({ok:false,version:VERSION,error:"match_id_client_nonce_expected_revision_required"},400);const b=await getBundle(matchId);if(b.revision!==expected)return json({ok:false,version:VERSION,error:"stale_revision",expected:b.revision,received:expected},409);const state=structuredClone(b.state);const actor=b.players.find((p:any)=>p.user_id===userId);if(!actor)return json({ok:false,version:VERSION,error:"not_match_participant"},403);const seat=Number(actor.seat),p=state.players[String(seat)];
   if(action==="opening_choice"){if(state.phase!=="opening_choice"||state.toss_winner_seat!==seat)return json({ok:false,version:VERSION,error:"opening_choice_not_allowed"},400);const choice=String(body.choice||"");if(!["first","second"].includes(choice))return json({ok:false,version:VERSION,error:"choice_must_be_first_or_second"},400);state.first_player_seat=choice==="first"?seat:(seat===1?2:1);state.phase="setup";state.setup_turn_seat=1;state.log.push(`Seat ${seat} chose to go ${choice}.`);const r=await commit(b,userId,nonce,action,state,"opening_choice",{seat,choice,first_player_seat:state.first_player_seat});return json({version:VERSION,result:r})}
   if(action==="setup_place"){if(state.phase!=="setup"||state.setup_turn_seat!==seat)return json({ok:false,version:VERSION,error:"setup_not_your_turn"},400);const uid=String(body.card_uid||""),where=String(body.where||""),idx=Number(body.index);const hi=p.hand.findIndex((x:Inst)=>x.uid===uid);if(hi<0)return json({ok:false,version:VERSION,error:"card_not_in_hand"},400);const inst=p.hand[hi],meta=state.card_index[inst.card_id];if(!starterLegal(meta))return json({ok:false,version:VERSION,error:"illegal_setup_creature"},400);if(where==="vanguard"){if(p.vanguard)return json({ok:false,version:VERSION,error:"vanguard_occupied"},400);p.vanguard=creatureFrom(inst)}else if(where==="reserve"){if(!Number.isInteger(idx)||idx<0||idx>3||p.reserve[idx])return json({ok:false,version:VERSION,error:"illegal_reserve_slot"},400);p.reserve[idx]=creatureFrom(inst)}else return json({ok:false,version:VERSION,error:"unknown_setup_zone"},400);p.hand.splice(hi,1);const r=await commit(b,userId,nonce,action,state,"setup_place",{seat,where,index:where==="reserve"?idx:null});return json({version:VERSION,result:r})}
   if(action==="setup_return"){if(state.phase!=="setup"||state.setup_turn_seat!==seat)return json({ok:false,version:VERSION,error:"setup_not_your_turn"},400);const where=String(body.where||""),idx=Number(body.index);let cr:any=null;if(where==="vanguard"){cr=p.vanguard;p.vanguard=null}else if(where==="reserve"&&Number.isInteger(idx)&&idx>=0&&idx<4){cr=p.reserve[idx];p.reserve[idx]=null}if(!cr||!cr.stack?.length)return json({ok:false,version:VERSION,error:"setup_creature_not_found"},400);p.hand.push(cr.stack[cr.stack.length-1]);const r=await commit(b,userId,nonce,action,state,"setup_return",{seat,where,index:where==="reserve"?idx:null});return json({version:VERSION,result:r})}
   if(action==="setup_ready"){if(state.phase!=="setup"||state.setup_turn_seat!==seat)return json({ok:false,version:VERSION,error:"setup_not_your_turn"},400);if(!p.vanguard)return json({ok:false,version:VERSION,error:"vanguard_required"},400);state.setup_ready[String(seat)]=true;if(seat===1){state.setup_turn_seat=2;state.log.push("Seat 1 setup locked.")}else{for(const s of [1,2]){const pp=state.players[String(s)];pp.rewards=pp.deck.splice(0,6)}state.phase="play";state.setup_turn_seat=null;state.active_seat=state.first_player_seat;state.turn_seq=1;state.personal_turns[String(state.active_seat)]=1;const ap=state.players[String(state.active_seat)];if(ap.deck.length<1)return json({ok:false,version:VERSION,error:"deck_depleted_before_start_draw"},400);ap.hand.push(ap.deck.shift());state.log.push(`Seat 2 setup locked. Seat ${state.active_seat} begins turn 1 and draws.`)}const r=await commit(b,userId,nonce,action,state,"setup_ready",{seat,all_ready:state.phase==="play"});return json({version:VERSION,result:r})}
   if(action==="end_turn"){if(state.phase!=="play"||state.active_seat!==seat)return json({ok:false,version:VERSION,error:"not_active_player"},400);const next=seat===1?2:1;state.active_seat=next;state.turn_seq=Number(state.turn_seq||0)+1;state.personal_turns[String(next)]=Number(state.personal_turns[String(next)]||0)+1;const np=state.players[String(next)];if(np.deck.length<1)return json({ok:false,version:VERSION,error:"deck_depletion_loss_pending_engine"},400);np.hand.push(np.deck.shift());state.log.push(`Seat ${next} begins personal turn ${state.personal_turns[String(next)]}.`);const r=await commit(b,userId,nonce,action,state,"end_turn",{from:seat,to:next});return json({version:VERSION,result:r})}
  }
  return json({ok:false,version:VERSION,error:"unknown_action"},400);
 }catch(e){return json({ok:false,version:VERSION,error:e instanceof Error?e.message:String(e)},500)}
});