import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const V="Code Labs Sol Chat V141",KEY=Deno.env.get("OPENAI_API_KEY")||"",MODEL=Deno.env.get("OPENAI_MODEL")||"gpt-5.1";
const ORIGINS=new Set(["https://chatterfriendsstreambandit.co.uk","https://www.chatterfriendsstreambandit.co.uk"]);
const tools=[
 {type:"function",name:"read_live_code_labs_page",description:"Read a fresh safe snapshot of the current Code Labs page before deciding what to do.",strict:true,parameters:{type:"object",properties:{},required:[],additionalProperties:false}},
 {type:"function",name:"write_live_code_labs_fields",description:"Write the smallest safe set of normal Code Labs fields by stable field key. Never write secrets or file inputs.",strict:true,parameters:{type:"object",properties:{expected_page:{type:"string"},expected_page_fingerprint:{type:"string"},fields:{type:"array",items:{type:"object",properties:{key:{type:"string"},value:{type:["string","number","boolean","null"]}},required:["key","value"],additionalProperties:false}}},required:["expected_page","expected_page_fingerprint","fields"],additionalProperties:false}},
 {type:"function",name:"write_live_code_labs_section",description:"Write safe fields belonging to one named Code Labs section.",strict:true,parameters:{type:"object",properties:{expected_page_fingerprint:{type:"string"},section_key:{type:"string"},fields:{type:"array",items:{type:"object",properties:{key:{type:"string"},value:{type:["string","number","boolean","null"]}},required:["key","value"],additionalProperties:false}}},required:["expected_page_fingerprint","section_key","fields"],additionalProperties:false}},
 {type:"function",name:"run_live_code_labs_action",description:"Press one page action by stable action key. Dangerous actions require explicit confirmation in the current user message.",strict:true,parameters:{type:"object",properties:{expected_page_fingerprint:{type:"string"},action_key:{type:"string"},confirmed:{type:"boolean"},allow_dangerous:{type:"boolean"}},required:["expected_page_fingerprint","action_key","confirmed","allow_dangerous"],additionalProperties:false}},
 {type:"function",name:"undo_live_code_labs_write",description:"Undo the most recent V140 page-field write on the unchanged current page.",strict:true,parameters:{type:"object",properties:{},required:[],additionalProperties:false}}
];
function cors(req:Request){const o=req.headers.get("origin")||"",a=ORIGINS.has(o)?o:"https://chatterfriendsstreambandit.co.uk";return{"Access-Control-Allow-Origin":a,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json","Cache-Control":"no-store"}})}
function text(v:unknown,n:number){return String(v==null?"":v).slice(0,n)}
function compact(v:unknown){if(!v||typeof v!=="object")return{};const p=v as Record<string,unknown>,x={page:p.page,page_fingerprint:p.page_fingerprint,title:p.title,url:p.url,repo:p.repo,path:p.path,source_branch:p.source_branch,request_branch:p.request_branch,action:p.action,problem:p.problem,preserve_rules:p.preserve_rules,error_notes:p.error_notes,test_notes:p.test_notes,counts:p.counts,sections:p.sections,fields:p.fields,actions:p.actions,current_source:p.current_source,fixed_output:p.fixed_output,github_writer:p.github_writer,github_lane:p.github_lane,safety_rules:p.safety_rules};return JSON.parse(text(JSON.stringify(x),260000))}
function instructions(){return["You are Sol inside Code Labs, a workbench for a non-coder.","Be direct, patient and practical. Read before writing.","Use live page tools instead of asking the user to copy or patch code manually.","For page edits, write the smallest field set, inspect the receipt, then read again before claiming success.","Never invent field or action keys.","Never handle passwords, tokens, API keys, private keys, login prompts, CAPTCHA or local file selections.","Never claim a repository, deployment or database change happened unless a tool receipt proves it.","Repository changes remain branch-and-pull-request only.","Delete, remove, publish, deploy, merge, send, submit and production actions require explicit confirmation of that exact action in the current message.","Do not expose secrets or hidden reasoning."].join("\n")}
function outputText(r:Record<string,unknown>){if(typeof r.output_text==="string")return r.output_text;const out=Array.isArray(r.output)?r.output as Array<Record<string,unknown>>:[],parts:string[]=[];for(const i of out){if(i.type!=="message"||!Array.isArray(i.content))continue;for(const c of i.content as Array<Record<string,unknown>>)if(c.type==="output_text"&&typeof c.text==="string")parts.push(c.text)}return parts.join("\n").trim()}
function calls(r:Record<string,unknown>){const out=Array.isArray(r.output)?r.output as Array<Record<string,unknown>>:[];return out.filter(i=>i.type==="function_call").map(i=>{let a={};try{a=JSON.parse(String(i.arguments||"{}"))}catch{}return{call_id:String(i.call_id||""),name:String(i.name||""),arguments:a}}).filter(i=>i.call_id&&i.name)}
async function openai(body:Record<string,unknown>){const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||`OpenAI request failed (${r.status})`);return d as Record<string,unknown>}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"POST required"},405);try{const b=await req.json().catch(()=>({})) as Record<string,unknown>,action=text(b.action||"chat",40);if(action==="health")return json(req,{ok:true,version:V,configured:Boolean(KEY),model:MODEL});if(!KEY)return json(req,{ok:false,error:"Code Labs Sol is waiting for its server-side OpenAI key."},503);const prev=text(b.previous_response_id,160)||undefined;let input:unknown;if(action==="tool_outputs"){const o=Array.isArray(b.tool_outputs)?b.tool_outputs:[];input=o.slice(0,8).map(v=>{const x=v as Record<string,unknown>;return{type:"function_call_output",call_id:text(x.call_id,160),output:text(x.output,120000)}})}else{const m=text(b.message,12000);if(!m.trim())return json(req,{ok:false,error:"Message required"},400);input=`CODE LABS LIVE CONTEXT\n${text(JSON.stringify({live_page:compact(b.page),recent_visible_chat:Array.isArray(b.history)?b.history.slice(-10):[],user_request:m}),300000)}`}const request:Record<string,unknown>={model:MODEL,instructions:instructions(),input,tools,tool_choice:"auto",parallel_tool_calls:false,max_output_tokens:6000,store:true};if(prev)request.previous_response_id=prev;const r=await openai(request);return json(req,{ok:true,version:V,model:r.model||MODEL,response_id:r.id||"",text:outputText(r),tool_calls:calls(r),usage:r.usage||null})}catch(e){return json(req,{ok:false,error:String((e as Error).message||e),version:V},500)}});
