import{applyRuntimeV02HealPacket,runtimeV02CurrentTurnHealPackets,type RuntimeV02HealPacket}from'./tcg-match-heal-packet-v0-2.ts';
import{runtimeV02Definition}from'./tcg-runtime-registry-v0-2.ts';
import{addRuntimeShield}from'../tcg-tactic-actions/runtime-v0-2-core.ts';
type I={uid:string;card_id:string;effect_flags?:Record<string,unknown>};type F={seat:1|2;where:'vanguard'|'reserve';index:number|null;cr:any;top:I;def:any};type C={kind:'ability'|'essence'|'realm';source:I;seat:1|2;field:F|null;listener:any};
const O=(v:any)=>v&&typeof v==='object'&&!Array.isArray(v)?v:null,E=(m:string):never=>{throw new Error(m)},S=(v:any,m:string)=>typeof v==='string'&&v.trim()?v.trim():E(m),SEAT=(v:any,m:string):1|2=>v===1||v===2?v:E(m),DEF=(s:any,i:any)=>runtimeV02Definition(s,i),ID=(c:C)=>S(c.listener.id,'tcg_v0_2_heal_listener_id_required');
function I(v:any,m:string):I{const x=O(v);if(!x)E(m);S(x.uid,m+':uid');S(x.card_id,m+':card_id');return x as I}
function on(s:any){const x=O(s.card_index),id=x&&Object.keys(x)[0];return!!(id&&DEF(s,id))}
function FS(s:any){const ps=O(s.players);if(!ps)E('tcg_v0_2_heal_listener_players_required');const a:F[]=[];for(const n of[1,2]as const){const p=O(ps[String(n)]);if(!p)E('tcg_v0_2_heal_listener_player_required');const r=p.reserve;if(r!=null&&!Array.isArray(r))E('tcg_v0_2_heal_listener_reserve_invalid');const z:any[]=[['vanguard',null,p.vanguard],...[0,1,2,3].map(i=>['reserve',i,Array.isArray(r)?r[i]:null])];for(const[where,index,v]of z){if(v==null)continue;const cr=O(v);if(!cr||!Array.isArray(cr.stack)||!cr.stack.length)E('tcg_v0_2_heal_listener_creature_invalid');const top=I(cr.stack.at(-1),'tcg_v0_2_heal_listener_top_invalid'),def=DEF(s,top);if(!def)E('tcg_v0_2_heal_listener_definition_missing');a.push({seat:n,where,index,cr,top,def}as F)}}return a}
function add(a:C[],kind:C['kind'],source:I,seat:1|2,field:F|null,list:any){if(list==null)return;if(!Array.isArray(list))E('tcg_v0_2_heal_listener_list_invalid');for(const q of list){const l=O(q);if(!l)E('tcg_v0_2_heal_listener_invalid');if(String(l.event||'')!=='after_heal_packet')continue;S(l.id,'tcg_v0_2_heal_listener_id_required');a.push({kind,source,seat,field,listener:l})}}
function CS(s:any){const a:C[]=[];for(const f of FS(s)){const cr=O(f.def.creature),ab=O(cr?.ability);if(ab&&String(ab.event||'')==='after_heal_packet'){if(String(ab.mode||'')!=='triggered')E('tcg_v0_2_heal_listener_ability_mode_unsupported');a.push({kind:'ability',source:f.top,seat:f.seat,field:f,listener:ab})}if(f.cr.essence!=null&&!Array.isArray(f.cr.essence))E('tcg_v0_2_heal_listener_essence_zone_invalid');for(const q of f.cr.essence||[]){const x=I(q,'tcg_v0_2_heal_listener_essence_invalid'),d=DEF(s,x),e=O(d?.essence);if(!d||String(d.card_family||'')!=='Essence'||!e)E('tcg_v0_2_heal_listener_essence_definition_invalid');add(a,'essence',x,f.seat,f,e.listeners)}}const r=O(s.realm);if(r){const x=I(r.card,'tcg_v0_2_heal_listener_realm_invalid'),d=DEF(s,x),t=O(d?.tactic);if(!d||!t)E('tcg_v0_2_heal_listener_realm_definition_invalid');add(a,'realm',x,SEAT(r.owner_seat,'tcg_v0_2_heal_listener_realm_owner_invalid'),null,t.listeners)}const seen=new Set;for(const c of a){const k=c.source.uid+':'+ID(c);if(seen.has(k))E('tcg_v0_2_heal_listener_duplicate_source');seen.add(k)}return a}
function P(v:any,p:RuntimeV02HealPacket,c:C):boolean{const x=O(v);if(!x)E('tcg_v0_2_heal_listener_requirement_invalid');if('all'in x){if(Object.keys(x).length!==1||!Array.isArray(x.all))E('tcg_v0_2_heal_listener_all_invalid');return x.all.every((q:any)=>P(q,p,c))}if('any'in x){if(Object.keys(x).length!==1||!Array.isArray(x.any)||!x.any.length)E('tcg_v0_2_heal_listener_any_invalid');return x.any.some((q:any)=>P(q,p,c))}const k=S(x.predicate,'tcg_v0_2_heal_listener_predicate_required'),u=c.field?.top.uid,d=c.field?.def,cr=O(d?.creature);switch(k){case'heal_packet_target_is_self':return!!u&&p.target.creature_uid===u;case'heal_source_is_card_effect':return p.source.card_effect===true;case'heal_actual_amount_at_least':{const n=Number(x.value);if(!Number.isFinite(n)||n<0)E('tcg_v0_2_heal_listener_heal_minimum_invalid');return p.actual_amount>=n}case'heal_packet_source_is_attached_creature':return!!u&&p.source.creature_uid===u;case'heal_packet_target_controller_is_self':return p.target.controller_seat===c.seat;case'heal_packet_target_is_not_source':return p.target.creature_uid!==p.source.creature_uid;case'heal_packet_source_action_kind_is':return p.source.action_kind===S(x.action_kind,'tcg_v0_2_heal_listener_action_kind_required');case'target_stage_in':if(String(x.target)!=='$attached_creature'||!Array.isArray(x.stages)||!x.stages.length)E('tcg_v0_2_heal_listener_stage_metadata_invalid');return x.stages.map(String).includes(String(cr?.stage||''));case'target_element_is':if(String(x.target)!=='$attached_creature')E('tcg_v0_2_heal_listener_element_target_unsupported');return String(d?.element||'')===String(x.element||'');case'heal_target_element_is':return p.target.element===String(x.element||'');case'heal_controller_is_active_seat':return p.controller_seat===p.active_seat;default:return E('tcg_v0_2_heal_listener_predicate_unsupported:'+k)}}
function M(c:C,p:RuntimeV02HealPacket){if(c.kind==='ability'){const t=c.listener.timing==null?'any':String(c.listener.timing);if(t==='own_turn'&&c.seat!==p.active_seat)return false;if(!['own_turn','any','passive'].includes(t))E('tcg_v0_2_heal_listener_timing_unsupported')}const q=c.listener.controller_scope;if(q!=null&&String(q)!=='any'&&!(String(q)==='self'&&p.controller_seat===c.seat))E('tcg_v0_2_heal_listener_controller_scope_unsupported');return c.listener.requirements==null||P(c.listener.requirements,p,c)}
function L(c:C,p:RuntimeV02HealPacket){const x=O(c.listener.limit);if(!x)return null;if(String(x.scope)!=='turn')E('tcg_v0_2_heal_listener_limit_scope_unsupported');const n=Number(x.count),o=String(x.owner);if(!Number.isInteger(n)||n<1)E('tcg_v0_2_heal_listener_limit_count_invalid');let k;if(o==='card_instance')k='card_instance:'+c.source.uid;else if(o==='attachment'){if(c.kind!=='essence')E('tcg_v0_2_heal_listener_attachment_owner_requires_attachment');k='attachment:'+c.source.uid}else if(o==='event_controller')k='event_controller:'+p.controller_seat;else E('tcg_v0_2_heal_listener_limit_owner_unsupported');return{count:n,owner:o,key:ID(c)+':'+k}}
function ST(c:C,n:'runtime_v0_2_listener_limits'|'runtime_v0_2_listener_receipts',make=false){if(c.source.effect_flags==null){if(!make)return null;c.source.effect_flags={}}const f=O(c.source.effect_flags);if(!f)E('tcg_v0_2_heal_listener_source_flags_invalid');if(f[n]==null){if(!make)return null;f[n]={}}const s=O(f[n]);if(!s)E('tcg_v0_2_heal_listener_state_invalid');return s}
function R(c:C,p:RuntimeV02HealPacket){const r=O(ST(c,'runtime_v0_2_listener_receipts')?.[ID(c)+':'+p.id]);if(!r)return false;if(r.packet_id!==p.id||r.listener_id!==c.listener.id||Number(r.turn_seq)!==p.turn_seq)E('tcg_v0_2_heal_listener_receipt_invalid');return true}
function MARK(c:C,p:RuntimeV02HealPacket){ST(c,'runtime_v0_2_listener_receipts',true)![ID(c)+':'+p.id]={packet_id:p.id,listener_id:ID(c),turn_seq:p.turn_seq}}
function USED(c:C,l:any,p:RuntimeV02HealPacket){const r=O(ST(c,'runtime_v0_2_listener_limits')?.[l.key]);if(!r)return 0;const t=Number(r.turn_seq),n=Number(r.count);if(!Number.isInteger(t)||!Number.isInteger(n)||n<0)E('tcg_v0_2_heal_listener_limit_counter_invalid');return t===p.turn_seq?n:0}
function USE(c:C,l:any,p:RuntimeV02HealPacket){const n=USED(c,l,p);if(n>=l.count)E('tcg_v0_2_heal_listener_limit_already_consumed');ST(c,'runtime_v0_2_listener_limits',true)![l.key]={turn_seq:p.turn_seq,count:n+1,owner:l.owner,listener_id:ID(c)}}
function SS(c:C){if(!Array.isArray(c.listener.steps)||!c.listener.steps.length)E('tcg_v0_2_heal_listener_steps_required');return c.listener.steps.map((q:any)=>O(q)||E('tcg_v0_2_heal_listener_step_invalid'))}
function T(c:C,t:any):F{const x=String(t||'');if(x==='$source_creature'&&c.kind==='ability'&&c.field)return c.field;if(x==='$attached_creature'&&c.kind==='essence'&&c.field)return c.field;return E('tcg_v0_2_heal_listener_target_unsupported:'+x)}
function DO(s:any,c:C,x:any){const op=String(x.op||''),f=T(c,x.target),n=Number(x.amount);if(!Number.isFinite(n)||n<=0)E('tcg_v0_2_heal_listener_amount_invalid');if(op==='ADD_SHIELD')return{op,target_creature_uid:f.top.uid,amount:n,actual_gain:addRuntimeShield(f.cr,n)};if(op==='HEAL'){const h=applyRuntimeV02HealPacket(s,f.cr,n,{source:{controller_seat:c.seat,action_kind:c.kind,action_id:ID(c),card_effect:true,card_uid:c.source.uid,card_id:c.source.card_id,creature_uid:c.field?.top.uid||null},target:{controller_seat:f.seat,creature_uid:f.top.uid,card_uid:f.top.uid,card_id:f.top.card_id,element:S(f.def.element,'tcg_v0_2_heal_listener_target_element_required'),where:f.where,index:f.index}});return{op,target_creature_uid:f.top.uid,amount:n,actual_heal:h.actual_heal,emitted_packet_id:h.packet?.id||null}}E('tcg_v0_2_heal_listener_step_unsupported:'+op)}
function CH(x:any,c:C,p:RuntimeV02HealPacket):1|2{if(!Array.isArray(x.steps)||!x.steps.length)E('tcg_v0_2_heal_listener_optional_steps_required');const q=String(x.player||'');if(q==='$event_controller')return p.controller_seat;if(q==='self')return c.seat;if(q==='opponent')return c.seat===1?2:1;return E('tcg_v0_2_heal_listener_optional_player_unsupported')}
export function dispatchRuntimeV02AfterHealPacket(s:Record<string,unknown>,packetId:string):any{if(!on(s))return null;const id=S(packetId,'tcg_v0_2_heal_listener_packet_id_required'),found=runtimeV02CurrentTurnHealPackets(s).find((x:RuntimeV02HealPacket)=>x.id===id);if(!found)throw new Error('tcg_v0_2_heal_listener_packet_not_found:'+id);const p=found,out:any={packet_id:id,resolved:[],deferred:[],limited:[],already_resolved:[],emitted_packet_ids:[]};for(const c of CS(s)){if(!M(c,p))continue;const base={listener_id:ID(c),source_uid:c.source.uid,source_card_id:c.source.card_id,source_kind:c.kind,controller_seat:c.seat};if(R(c,p)){out.already_resolved.push({listener_id:ID(c),source_uid:c.source.uid});continue}const l=L(c,p);if(l&&USED(c,l,p)>=l.count){out.limited.push({...base,limit_owner:l.owner});continue}const ss=SS(c),opt=ss.find((x:any)=>String(x.op||'')==='OPTIONAL');if(opt){if(ss.length!==1)E('tcg_v0_2_heal_listener_mixed_choice_program_unsupported');out.deferred.push({...base,chooser_seat:CH(opt,c,p),reason:'player_choice_required',limit_owner:l?.owner||null});continue}const effects=ss.map((x:any)=>DO(s,c,x));MARK(c,p);if(l)USE(c,l,p);for(const x of effects)if(x.op==='HEAL'&&x.emitted_packet_id)out.emitted_packet_ids.push(x.emitted_packet_id);out.resolved.push({...base,limit_owner:l?.owner||null,effects})}return out}
