import { createClient } from "jsr:@supabase/supabase-js@2";

const VERSION="Stream Bandit TCG match actions v0.3";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const env=(n:string)=>Deno.env.get(n)||"";
function firstKey(raw:string){if(!raw)return"";try{const x=JSON.parse(raw);if(typeof x==="string")return x;const vals=Array.isArray(x)?x:Object.values(x||{});for(const it of vals){if(typeof it==="string")return it;if(it&&typeof it==="object"){const o=it as Record<string,unknown>;for(const k of ["value","key","secret","api_key"])if(typeof o[k]==="string")return o[k] as string}}}catch{return raw}return""}
const need=(n:string,v:string)=>{if(!v)throw new Error(`Missing ${n}`);return v};
type Inst={uid:string,card_id:string,attached_turn?:number,borrowed?:boolean,effect_flags?:Record<string,unknown>};
type Cr={stack:Inst[],essence:Inst[],relic:Inst|null,damage:number,shield:number,condition?:string|null,conditions?:Record<string,unknown>,flags?:Record<string,unknown>,entered_turn?:number,evolved_turn?:number,became_vanguard_turn?:number};
type ParsedAttack={name:string,raw:string,typed:Record<string,number>,any:number,damage:number,effect:string,starbound:boolean};
function def(state:any,instOrId:any){const id=typeof instOrId==="string"?instOrId:instOrId?.card_id;return state.card_index?.[id]?.definition||state.card_index?.[id]||null}
function top(cr:Cr,state:any){return cr?.stack?.length?def(state,cr.stack[cr.stack.length-1]):null}
function starterLegal(d:any){return d?.kind==="Creature"&&["Baby","Standalone","Mythic"].includes(String(d.stage||""))}
function getCr(p:any,where:string,index:number|null){if(where==="vanguard")return p.vanguard as Cr|null;if(where==="reserve"&&Number.isInteger(index)&&Number(index)>=0&&Number(index)<4)return p.reserve[Number(index)] as Cr|null;return null}
function allCr(p:any){const out:{where:string,index:number|null,cr:Cr}[]=[];if(p.vanguard)out.push({where:"vanguard",index:null,cr:p.vanguard});for(let i=0;i<4;i++)if(p.reserve?.[i])out.push({where:"reserve",index:i,cr:p.reserve[i]});return out}
function removeHand(p:any,uid:string){const k=p.hand.findIndex((x:Inst)=>x.uid===uid);if(k<0)return null;return p.hand.splice(k,1)[0] as Inst}
function publicField(p:any){return{vanguard:p.vanguard,reserve:p.reserve,discard_count:p.discard.length,void_count:p.void.length,rewards_count:p.rewards.length,deck_count:p.deck.length,hand_count:p.hand.length}}
function makeView(s:any,viewerSeat:number,revision:number){const own=s.players[String(viewerSeat)],opp=s.players[String(viewerSeat===1?2:1)];return{version:s.version,match_id:s.match_id,revision,phase:s.phase,toss_winner_seat:s.toss_winner_seat,first_player_seat:s.first_player_seat,setup_turn_seat:s.setup_turn_seat,active_seat:s.active_seat,turn_seq:s.turn_seq,personal_turns:s.personal_turns,setup_ready:s.setup_ready,realm:s.realm,turn_flags:s.turn_flags||{},pending_resolution:s.pending_resolutions?.[0]?{kind:s.pending_resolutions[0].kind,seat:s.pending_resolutions[0].seat,count:s.pending_resolutions[0].count||null}:null,result:s.result||null,log:(s.log||[]).slice(-20),you:{seat:viewerSeat,user_id:own.user_id,hand:own.hand,deck_count:own.deck.length,rewards_count:own.rewards.length,vanguard:own.vanguard,reserve:own.reserve,discard:own.discard,void_count:own.void.length,mulligans:own.mulligans,deck_meta:own.deck_meta},opponent:{seat:opp.seat,user_id:opp.user_id,...publicField(opp),mulligans:opp.mulligans,deck_meta:{name:opp.deck_meta.name,primary_element:opp.deck_meta.primary_element}},card_index:s.card_index}}
function views(s:any,revision:number){return{p1:makeView(s,1,revision),p2:makeView(s,2,revision)}}
function ensureFlags(s:any,seat:number){s.turn_flags=s.turn_flags||{};const k=String(seat);s.turn_flags[k]=s.turn_flags[k]||{};return s.turn_flags[k]}
function addShield(cr:Cr,n:number){cr.shield=Math.min(60,Math.max(0,Number(cr.shield||0)+n))}
function heal(cr:Cr,n:number){cr.damage=Math.max(0,Number(cr.damage||0)-n)}
function conditions(cr:Cr){const q=(cr.conditions||={scorched:false,venomed:0,control:null,modifier:null}) as any;return q}
function clearCond(cr:Cr,c:string){const q=conditions(cr);if(c==="Scorched")q.scorched=false;else if(c==="Venomed")q.venomed=0;else if(q.control===c)q.control=null;else if(q.modifier===c)q.modifier=null}
function clearOrdinaryConditions(cr:Cr){cr.conditions={scorched:false,venomed:0,control:null,modifier:null};cr.condition=null}
function applyCondition(cr:Cr,c:string,s?:any){const f=(cr.flags||{}) as any;const immunity=f.lifecycle_condition_immunity;if(immunity&&Number(immunity.turn_seq)===Number(s?.turn_seq??-1)&&Array.isArray(immunity.conditions)&&immunity.conditions.includes(c))return false;const q=conditions(cr);if(c==="Scorched")q.scorched=true;else if(c==="Venomed")q.venomed=Math.max(10,Number(q.venomed||0));else if(["Stunned","Dazed","Rooted","Blinded","Mindbound"].includes(c))q.control=c;else if(["Silenced","Drenched","Crushed"].includes(c))q.modifier=c;return true}
function hasCondition(cr:Cr,c?:string){const q=conditions(cr);if(c==="Scorched")return !!q.scorched;if(c==="Venomed")return Number(q.venomed||0)>0;if(c)return q.control===c||q.modifier===c;return !!q.scorched||Number(q.venomed||0)>0||!!q.control||!!q.modifier}
function isEvolved(d:any){return ["Teen","Adult"].includes(String(d?.stage||""))}
function essenceProvides(d:any){return String(d?.element||"")}
function randomCodeSafe(){return crypto.randomUUID()}
function coin(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%2===0?"heads":"tails"}
function maxHp(cr:Cr,s:any){return Math.max(0,Number(top(cr,s)?.hp||0))}
function rewardValue(cr:Cr,s:any){const d=top(cr,s);const explicit=Number(d?.reward_value);if(Number.isFinite(explicit)&&explicit>0)return explicit;if(String(d?.form||d?.class||"")==="Titan"||String(d?.stage||"")==="Titan")return 3;if(String(d?.stage||"")==="Mythic"||(Array.isArray(d?.traits)&&d.traits.includes("Mythic")))return 2;return 1}
function parseAttack(raw:string):ParsedAttack|null{const t=String(raw||"").trim();if(!t)return null;let cost="",name="",damage=0,effect="",starbound=false;let m=t.match(/^Starbound Power — ([^:]+):\s*(.*?) — (\d+)(?:;\s*(.*))?$/);if(m){starbound=true;name=m[1].trim();cost=m[2].trim();damage=Number(m[3]);effect=String(m[4]||"").trim()}else{m=t.match(/^(.*?) — (.*?) — (\d+)(?:;\s*(.*))?$/);if(!m)return null;cost=m[1].trim();name=m[2].trim();damage=Number(m[3]);effect=String(m[4]||"").trim()}const typed:Record<string,number>={};let any=0;for(const part of cost.split("+").map(x=>x.trim()).filter(Boolean)){const cm=part.match(/^(\d+)\s+([A-Za-z]+)$/);if(!cm)return null;const n=Number(cm[1]),e=cm[2];if(e.toLowerCase()==="any")any+=n;else typed[e]=(typed[e]||0)+n}return{name,raw:t,typed,any,damage,effect,starbound}}
function canPayAttack(cr:Cr,s:any,a:ParsedAttack){if(conditions(cr).modifier==="Drenched")return false;const counts:Record<string,number>={};for(const e of cr.essence||[]){const d=def(s,e),k=essenceProvides(d);if(k)counts[k]=(counts[k]||0)+1}let used=0;for(const [k,n] of Object.entries(a.typed)){if((counts[k]||0)<n)return false;used+=n}return (cr.essence?.length||0)-used>=a.any}
function withdrawalCost(cr:Cr,s:any){const d=top(cr,s);let n=Math.max(0,Number(d?.withdraw||0));let lockIncrease=false;for(const e of cr.essence||[]){const id=e.card_id;if(id==="gale-breeze-essence"||id==="grove-root-essence")n=Math.max(0,n-1);if(id==="stone-anchor-essence")n+=1;if(id==="stone-granite-essence")lockIncrease=true}if(conditions(cr).modifier==="Crushed"&&!lockIncrease)n+=1;const f=(cr.flags||{}) as any;if(Number.isFinite(Number(f.withdrawal_cost_override)))n=Math.max(0,Number(f.withdrawal_cost_override));const lifecycle=f.lifecycle_withdrawal_cost;if(lifecycle&&Number(lifecycle.turn_seq)===Number(s.turn_seq||0)&&Number.isFinite(Number(lifecycle.value)))n=Math.max(0,Number(lifecycle.value));return n}
function attackDamage(cr:Cr,target:Cr,s:any,base:number){let n=Math.max(0,base);const af=(cr.flags||{}) as any;n+=Number(af.next_attack_bonus||0);af.next_attack_bonus=0;const lifecycle=af.lifecycle_attack_bonus;if(lifecycle&&Number(lifecycle.turn_seq)===Number(s.turn_seq||0)){n+=Math.max(0,Number(lifecycle.amount||0));const uses=Math.max(1,Number(lifecycle.uses||1));if(uses>1)lifecycle.uses=uses-1;else delete af.lifecycle_attack_bonus}for(const e of cr.essence||[])if(e.card_id==="shade-whisper-essence"&&hasCondition(target))n+=10;const q=conditions(target);if(q.modifier==="Crushed"){n+=20;q.modifier=null}for(const e of target.essence||[])if(e.card_id==="stone-anchor-essence")n=Math.max(0,n-10);const shield=Math.max(0,Number(target.shield||0)),blocked=Math.min(shield,n);target.shield=shield-blocked;target.damage=Number(target.damage||0)+(n-blocked);return{dealt:n-blocked,blocked}}
function directDamage(cr:Cr,n:number){cr.damage=Number(cr.damage||0)+Math.max(0,n)}
function switchWithReserve(p:any,index:number,turn:number){if(!Number.isInteger(index)||index<0||index>3||!p.reserve?.[index])return false;const old=p.vanguard;p.vanguard=p.reserve[index];p.reserve[index]=old;if(old)clearOrdinaryConditions(old);if(p.vanguard){clearOrdinaryConditions(p.vanguard);p.vanguard.became_vanguard_turn=turn}return true}
function safeDiscardCreature(p:any,where:string,index:number|null,cr:Cr){p.discard.push(...(cr.stack||[]),...(cr.essence||[]));if(cr.relic)p.discard.push(cr.relic);if(where==="vanguard")p.vanguard=null;else if(where==="reserve"&&index!=null)p.reserve[index]=null}

Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return json({ok:false,version:VERSION,error:"POST only"},405);
 try{
  const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))return json({ok:false,version:VERSION,error:"signed_in_user_required"},401);
  const url=need("SUPABASE_URL",env("SUPABASE_URL"));const pub=need("publishable key",env("SUPABASE_ANON_KEY")||firstKey(env("SUPABASE_PUBLISHABLE_KEYS")));const svc=need("service role key",env("SUPABASE_SERVICE_ROLE_KEY")||firstKey(env("SUPABASE_SECRET_KEYS")));
  const user=createClient(url,pub,{global:{headers:{Authorization:auth}},auth:{autoRefreshToken:false,persistSession:false}});const admin=createClient(url,svc,{auth:{autoRefreshToken:false,persistSession:false}});
  const {data:ud,error:ue}=await user.auth.getUser();const userId=ud?.user?.id||"";if(ue||!userId)return json({ok:false,version:VERSION,error:"invalid_user_token"},401);
  let body:any={};try{body=await req.json()}catch{return json({ok:false,version:VERSION,error:"invalid_json"},400)}
  const action=String(body.action||"");if(action==="ping")return json({ok:true,version:VERSION,user_id:userId});
  const matchId=String(body.match_id||"");const nonce=String(body.client_nonce||"");const expected=Number(body.expected_revision);if(!matchId||!nonce||!Number.isInteger(expected)||expected<0)return json({ok:false,version:VERSION,error:"match_id_client_nonce_expected_revision_required"},400);
  const {data:prior,error:priorErr}=await admin.from("tcg_match_commands").select("status,result,expected_revision,resolved_at").eq("match_id",matchId).eq("user_id",userId).eq("client_nonce",nonce).maybeSingle();if(priorErr)throw priorErr;if(prior)return json({ok:true,version:VERSION,replayed:true,result:prior.result,status:prior.status});
  const [{data:st,error:se},{data:ps,error:pe}]=await Promise.all([admin.from("tcg_match_state_private").select("revision,canonical_state").eq("match_id",matchId).maybeSingle(),admin.from("tcg_match_players").select("user_id,seat").eq("match_id",matchId)]);if(se)throw se;if(pe)throw pe;if(!st||!ps?.length)return json({ok:false,version:VERSION,error:"match_not_found"},404);
  const revision=Number(st.revision);if(revision!==expected)return json({ok:false,version:VERSION,error:"stale_revision",expected:revision,received:expected},409);
  const actor=ps.find((x:any)=>x.user_id===userId);if(!actor)return json({ok:false,version:VERSION,error:"not_match_participant"},403);const seat=Number(actor.seat);const otherSeat=seat===1?2:1;const s=structuredClone(st.canonical_state as any);const p=s.players[String(seat)],opp=s.players[String(otherSeat)];
  const rpc=async(fn:string,args:any)=>{const {data,error}=await admin.rpc(fn,args);if(error)throw new Error(`${fn}: ${error.message}`);return data};
  const commit=async(eventType:string,payload:any)=>{const next=revision+1;const vv=views(s,next);return await rpc("tcg_server_commit_state",{p_match_id:matchId,p_actor_user_id:userId,p_client_nonce:nonce,p_expected_revision:revision,p_command_type:action,p_new_state:s,p_player_one_id:s.players["1"].user_id,p_player_one_view:vv.p1,p_player_two_id:s.players["2"].user_id,p_player_two_view:vv.p2,p_event_type:eventType,p_public_payload:payload||{}})};
  const log=(m:string)=>{s.log=s.log||[];s.log.push(m)};
  const queue=()=>{s.pending_resolutions=s.pending_resolutions||[];return s.pending_resolutions as any[]};
  const evaluateWinner=()=>{const reasons:Record<string,string[]>={"1":[],"2":[]};for(const who of [1,2]){const me=s.players[String(who)],them=s.players[String(who===1?2:1)];if((me.rewards?.length||0)===0)reasons[String(who)].push("all_rewards_taken");if(!them.vanguard&&!(them.reserve||[]).some(Boolean))reasons[String(who)].push("opponent_has_no_creature");if(Number(s.deckout_loser||0)===(who===1?2:1))reasons[String(who)].push("opponent_deckout")}const a=reasons["1"].length,b=reasons["2"].length;if(a===0&&b===0)return false;if(a>b){s.phase="complete";s.result={winner_seat:1,reasons:reasons["1"]};return true}if(b>a){s.phase="complete";s.result={winner_seat:2,reasons:reasons["2"]};return true}s.phase="overtime_pending";s.result={winner_seat:null,reasons,reason:"simultaneous_win_tie_requires_overtime"};return true};
  const scanDefeats=()=>{const defeated:any[]=[];for(const who of [1,2]){const owner=s.players[String(who)];for(const x of allCr(owner)){const hp=maxHp(x.cr,s);if(hp>0&&Number(x.cr.damage||0)>=hp)defeated.push({ownerSeat:who,...x,reward:rewardValue(x.cr,s),name:top(x.cr,s)?.name||"Creature"})}}for(const d of defeated){safeDiscardCreature(s.players[String(d.ownerSeat)],d.where,d.index,d.cr);const receiver=d.ownerSeat===1?2:1;const available=s.players[String(receiver)].rewards?.length||0;if(available>0)queue().push({kind:"take_reward",seat:receiver,count:Math.min(d.reward,available),source:d.name});log(`${d.name} was defeated.`)}for(const who of [1,2]){const owner=s.players[String(who)];if(!owner.vanguard&&(owner.reserve||[]).some(Boolean))queue().push({kind:"promote",seat:who})}return defeated.length};
  const advanceTurn=()=>{if(evaluateWinner())return;const from=Number(s.active_seat),next=from===1?2:1;s.active_seat=next;s.turn_seq=Number(s.turn_seq||0)+1;s.personal_turns=s.personal_turns||{"1":0,"2":0};s.personal_turns[String(next)]=Number(s.personal_turns[String(next)]||0)+1;const np=s.players[String(next)];if(!np.deck?.length){s.deckout_loser=next;evaluateWinner();return}np.hand.push(np.deck.shift());log(`Seat ${next} begins personal turn ${s.personal_turns[String(next)]}.`)};
  const aftermath=(who:number)=>{const owner=s.players[String(who)],v=owner.vanguard as Cr|null,turn=Number(s.turn_seq||0);if(v){const q=conditions(v);if(q.scorched){directDamage(v,20);const r=coin();log(`Scorched dealt 20 to Seat ${who}'s Vanguard (${r}).`);if(r==="heads")q.scorched=false}if(Number(q.venomed||0)>0){const n=Math.min(60,Math.max(10,Number(q.venomed)));directDamage(v,n);q.venomed=Math.min(60,n+10);log(`Venomed dealt ${n} to Seat ${who}'s Vanguard.`)}if(q.control==="Stunned"||q.control==="Rooted")q.control=null;if(q.modifier==="Silenced"||q.modifier==="Crushed")q.modifier=null;if(q.modifier==="Drenched"&&coin()==="heads")q.modifier=null}for(const x of allCr(owner)){const cf=(x.cr.flags||{}) as any;if(cf.lifecycle_attack_bonus&&Number(cf.lifecycle_attack_bonus.turn_seq)===turn)delete cf.lifecycle_attack_bonus;if(cf.lifecycle_withdrawal_cost&&Number(cf.lifecycle_withdrawal_cost.turn_seq)===turn)delete cf.lifecycle_withdrawal_cost;if(cf.lifecycle_condition_immunity&&Number(cf.lifecycle_condition_immunity.turn_seq)===turn)delete cf.lifecycle_condition_immunity;const kept:Inst[]=[];for(const e of x.cr.essence||[]){const ef=(e.effect_flags||{}) as any;const generated=ef.discard_during_target_aftermath===true;const surge=x.where==="vanguard"&&e.card_id==="volt-surge-essence"&&Number(e.attached_turn??-1)===turn;if(generated||surge)owner.discard.push(e);else kept.push(e)}x.cr.essence=kept}const tf=ensureFlags(s,who);if(tf.lifecycle_attack_eligibility&&Number(tf.lifecycle_attack_eligibility.turn_seq)===turn)delete tf.lifecycle_attack_eligibility;const n=scanDefeats();if(n>0){s.phase="resolution";s.resume_after_resolution="turn_advance";return}advanceTurn()};
  const continueResolution=()=>{if(queue().length)return;if(evaluateWinner())return;const resume=String(s.resume_after_resolution||"");s.resume_after_resolution=null;if(resume==="aftermath")aftermath(Number(s.active_seat));else if(resume==="turn_advance")advanceTurn();else{s.phase="play"}};

  if(action==="concede"){if(s.phase==="complete")return json({ok:false,version:VERSION,error:"match_already_complete"},400);s.phase="complete";s.result={winner_seat:otherSeat,reasons:["opponent_conceded"]};log(`Seat ${seat} conceded.`);return json({version:VERSION,result:await commit("concede",{seat,winner_seat:otherSeat})})}

  if(action==="take_reward"){const q=queue()[0];if(s.phase!=="resolution"||!q||q.kind!=="take_reward"||Number(q.seat)!==seat)return json({ok:false,version:VERSION,error:"reward_resolution_not_yours"},400);const count=Math.min(Number(q.count||0),p.rewards?.length||0);const posRaw=Array.isArray(body.reward_positions)?body.reward_positions.map((x:any)=>Number(x)):[];if(posRaw.length!==count||new Set(posRaw).size!==count||posRaw.some((x:number)=>!Number.isInteger(x)||x<0||x>=p.rewards.length))return json({ok:false,version:VERSION,error:"exact_legal_reward_positions_required",count},400);const taken:Inst[]=[];for(const i of [...posRaw].sort((a:number,b:number)=>b-a))taken.push(p.rewards.splice(i,1)[0]);p.hand.push(...taken.reverse());queue().shift();log(`Seat ${seat} took ${count} Reward Card${count===1?"":"s"}.`);continueResolution();return json({version:VERSION,result:await commit("take_reward",{seat,count})})}

  if(action==="promote"){const q=queue()[0];if(s.phase!=="resolution"||!q||q.kind!=="promote"||Number(q.seat)!==seat)return json({ok:false,version:VERSION,error:"promotion_resolution_not_yours"},400);const idx=Number(body.reserve_index);if(!Number.isInteger(idx)||idx<0||idx>3||!p.reserve?.[idx]||p.vanguard)return json({ok:false,version:VERSION,error:"legal_reserve_promotion_required"},400);p.vanguard=p.reserve[idx];p.reserve[idx]=null;clearOrdinaryConditions(p.vanguard);p.vanguard.became_vanguard_turn=Number(s.turn_seq||0);queue().shift();log(`Seat ${seat} promoted Reserve ${idx+1} to Vanguard.`);continueResolution();return json({version:VERSION,result:await commit("promote",{seat,reserve_index:idx})})}

  if(s.phase!=="play"||Number(s.active_seat)!==seat)return json({ok:false,version:VERSION,error:"not_active_player"},400);const flags=ensureFlags(s,seat);

  if(action==="play_creature"){
   const uid=String(body.card_uid||""),idx=Number(body.reserve_index);if(!Number.isInteger(idx)||idx<0||idx>3||p.reserve[idx])return json({ok:false,version:VERSION,error:"empty_reserve_slot_required"},400);const inst=p.hand.find((x:Inst)=>x.uid===uid);const d=inst?def(s,inst):null;if(!inst||!starterLegal(d))return json({ok:false,version:VERSION,error:"baby_standalone_or_mythic_required"},400);const x=removeHand(p,uid)!;p.reserve[idx]={stack:[x],essence:[],relic:null,damage:0,shield:0,condition:null,conditions:{scorched:false,venomed:0,control:null,modifier:null},flags:{},entered_turn:Number(s.turn_seq||0),evolved_turn:-1};log(`Seat ${seat} played ${d.name} to Reserve ${idx+1}.`);return json({version:VERSION,result:await commit("play_creature",{seat,reserve_index:idx,card_id:d.id})});
  }

  if(action==="evolve"){
   if(Number(s.personal_turns?.[String(seat)]||0)<=1)return json({ok:false,version:VERSION,error:"evolution_locked_on_first_personal_turn"},400);const uid=String(body.card_uid||""),where=String(body.where||""),idx=body.index==null?null:Number(body.index),cr=getCr(p,where,idx);if(!cr)return json({ok:false,version:VERSION,error:"target_creature_not_found"},400);const inst=p.hand.find((x:Inst)=>x.uid===uid),d=inst?def(s,inst):null,prev=top(cr,s);if(!inst||!d||d.kind!=="Creature"||!["Teen","Adult"].includes(String(d.stage||"")))return json({ok:false,version:VERSION,error:"teen_or_adult_required"},400);if(String(d.evolves_from_id||"")!==String(prev?.id||""))return json({ok:false,version:VERSION,error:"evolution_predecessor_mismatch"},400);const turn=Number(s.turn_seq||0);if(Number(cr.entered_turn??0)>=turn)return json({ok:false,version:VERSION,error:"stack_entered_or_evolved_this_turn"},400);if(Number(cr.evolved_turn??-1)===turn)return json({ok:false,version:VERSION,error:"one_evolution_per_stack_per_turn"},400);const x=removeHand(p,uid)!;cr.stack.push(x);cr.evolved_turn=turn;cr.entered_turn=turn;clearOrdinaryConditions(cr);
   if(d.id==="tide-reefback"||d.id==="stone-cragroller")addShield(cr,20);else if(d.id==="grove-briarback"&&p.reserve.filter(Boolean).length>=2)heal(cr,30);else if(d.id==="shade-veiljaw"&&opp.vanguard){const q=conditions(opp.vanguard);if(!q.control)q.control="Dazed"}
   log(`Seat ${seat} evolved ${prev.name} into ${d.name}.`);return json({version:VERSION,result:await commit("evolve",{seat,where,index:idx,from_card_id:prev.id,to_card_id:d.id})});
  }

  if(action==="attach_essence"){
   const turn=Number(s.turn_seq||0);if(Number(flags.manual_essence_turn??-1)===turn)return json({ok:false,version:VERSION,error:"manual_essence_already_used_this_turn"},400);const uid=String(body.card_uid||""),where=String(body.where||""),idx=body.index==null?null:Number(body.index),cr=getCr(p,where,idx);if(!cr)return json({ok:false,version:VERSION,error:"target_creature_not_found"},400);const inst=p.hand.find((x:Inst)=>x.uid===uid),d=inst?def(s,inst):null;if(!inst||!d||d.kind!=="Essence")return json({ok:false,version:VERSION,error:"essence_card_required"},400);const x=removeHand(p,uid)!;x.attached_turn=turn;cr.essence.push(x);flags.manual_essence_turn=turn;const td=top(cr,s);
   if(d.id==="ember-smolder-essence"&&cr.damage>0){cr.flags=cr.flags||{};cr.flags.next_attack_bonus=(Number((cr.flags as any).next_attack_bonus||0)+10)}else if(d.id==="ember-hearth-essence"&&cr.damage>0)heal(cr,20);else if(d.id==="tide-calm-essence"&&td?.element==="Tide")heal(cr,20);else if(d.id==="grove-bloom-essence"&&td?.element==="Grove"&&isEvolved(td))heal(cr,20);else if(d.id==="stone-fault-essence"&&td?.element==="Stone")clearCond(cr,"Crushed");
   if(td?.id==="tide-puddlepip"&&d.element==="Tide"){cr.flags=cr.flags||{};const f=cr.flags as any;if(Number(f.freshwater_turn??-1)!==turn){f.freshwater_turn=turn;heal(cr,10)}}
   log(`Seat ${seat} attached ${d.name} to ${td?.name||"a creature"}.`);return json({version:VERSION,result:await commit("attach_essence",{seat,where,index:idx,card_id:d.id,provides:essenceProvides(d)})});
  }

  if(action==="attach_relic"){
   const uid=String(body.card_uid||""),where=String(body.where||""),idx=body.index==null?null:Number(body.index),cr=getCr(p,where,idx);if(!cr)return json({ok:false,version:VERSION,error:"target_creature_not_found"},400);if(cr.relic)return json({ok:false,version:VERSION,error:"creature_already_has_relic"},400);const inst=p.hand.find((x:Inst)=>x.uid===uid),d=inst?def(s,inst):null;if(!inst||!d||d.kind!=="Tactic"||d.family!=="Relic")return json({ok:false,version:VERSION,error:"relic_card_required"},400);cr.relic=removeHand(p,uid)!;const td=top(cr,s);if(td?.id==="stone-flintkin")heal(cr,10);log(`Seat ${seat} attached ${d.name} to ${td?.name||"a creature"}.`);return json({version:VERSION,result:await commit("attach_relic",{seat,where,index:idx,card_id:d.id})});
  }

  if(action==="play_realm"){
   const turn=Number(s.turn_seq||0);if(Number(flags.realm_turn??-1)===turn)return json({ok:false,version:VERSION,error:"realm_already_played_this_turn"},400);const uid=String(body.card_uid||""),inst=p.hand.find((x:Inst)=>x.uid===uid),d=inst?def(s,inst):null;if(!inst||!d||d.kind!=="Tactic"||d.family!=="Realm")return json({ok:false,version:VERSION,error:"realm_card_required"},400);if(s.realm){const old=def(s,s.realm.card);if(old?.id===d.id)return json({ok:false,version:VERSION,error:"same_named_realm_cannot_replace_itself"},400);const owner=s.players[String(s.realm.owner_seat)];if(owner)owner.discard.push(s.realm.card)}s.realm={card:removeHand(p,uid)!,owner_seat:seat,played_turn:turn};flags.realm_turn=turn;log(`Seat ${seat} played Realm ${d.name}.`);return json({version:VERSION,result:await commit("play_realm",{seat,card_id:d.id})});
  }

  if(action==="withdraw"){
   const turn=Number(s.turn_seq||0);if(Number(flags.withdraw_turn??-1)===turn)return json({ok:false,version:VERSION,error:"withdrawal_already_used_this_turn"},400);if(!p.vanguard)return json({ok:false,version:VERSION,error:"vanguard_required"},400);const cq=conditions(p.vanguard);if(cq.control==="Stunned"||cq.control==="Rooted")return json({ok:false,version:VERSION,error:"condition_prevents_withdrawal"},400);const idx=Number(body.reserve_index);if(!Number.isInteger(idx)||idx<0||idx>3||!p.reserve?.[idx])return json({ok:false,version:VERSION,error:"legal_reserve_required"},400);const cost=withdrawalCost(p.vanguard,s);const uids=Array.isArray(body.discard_essence_uids)?body.discard_essence_uids.map((x:any)=>String(x)):[];if(uids.length!==cost||new Set(uids).size!==cost)return json({ok:false,version:VERSION,error:"exact_withdrawal_essence_payment_required",cost},400);for(const uid of uids)if(!p.vanguard.essence.some((e:Inst)=>e.uid===uid))return json({ok:false,version:VERSION,error:"withdrawal_payment_not_attached"},400);for(const uid of uids){const k=p.vanguard.essence.findIndex((e:Inst)=>e.uid===uid);p.discard.push(p.vanguard.essence.splice(k,1)[0])}const old=p.vanguard;p.vanguard=p.reserve[idx];p.reserve[idx]=old;clearOrdinaryConditions(old);clearOrdinaryConditions(p.vanguard);p.vanguard.became_vanguard_turn=turn;flags.withdraw_turn=turn;log(`Seat ${seat} withdrew to Reserve ${idx+1}, paying ${cost} Essence.`);return json({version:VERSION,result:await commit("withdraw",{seat,reserve_index:idx,cost})});
  }

  if(action==="end_turn"){
   aftermath(seat);return json({version:VERSION,result:await commit("end_turn",{seat})});
  }

  if(action==="attack"){
   if(!p.vanguard)return json({ok:false,version:VERSION,error:"vanguard_required"},400);if(Number(s.first_player_seat)===seat&&Number(s.personal_turns?.[String(seat)]||0)<=1)return json({ok:false,version:VERSION,error:"first_player_cannot_attack_on_first_personal_turn"},400);const eligibility=flags.lifecycle_attack_eligibility;if(eligibility&&Number(eligibility.turn_seq)===Number(s.turn_seq||0)&&String(eligibility.mode)==="final_vanguard_only"){const anchor=String(eligibility.anchor_uid||"");if(!anchor||!(p.vanguard.stack||[]).some((x:Inst)=>x.uid===anchor))return json({ok:false,version:VERSION,error:"only_final_vanguard_may_attack_this_turn"},400)}const slot=Number(body.attack_slot);if(slot!==1&&slot!==2)return json({ok:false,version:VERSION,error:"attack_slot_must_be_1_or_2"},400);const ad=top(p.vanguard,s),raw=String(ad?.[`attack_${slot}`]||"");const atk=parseAttack(raw);if(!atk)return json({ok:false,version:VERSION,error:"attack_definition_unparseable"},400);if(!canPayAttack(p.vanguard,s,atk))return json({ok:false,version:VERSION,error:"attack_essence_cost_not_met"},400);if(atk.starbound){p.match_flags=p.match_flags||{};if(p.match_flags.starbound_used)return json({ok:false,version:VERSION,error:"starbound_power_already_used"},400);if(s.timefold_lock_seat!=null)return json({ok:false,version:VERSION,error:"extra_turn_chain_blocked"},400);p.match_flags.starbound_used=true}
   const cq=conditions(p.vanguard);const randoms:any[]=[];if(cq.control==="Mindbound"){const r=coin();randoms.push({condition:"Mindbound",result:r});if(r==="heads")cq.control=null;else{directDamage(p.vanguard,60);log(`Mindbound dealt 60 to Seat ${seat}'s Vanguard and ended the attack.`);const n=scanDefeats();if(n>0){s.phase="resolution";s.resume_after_resolution="aftermath"}else aftermath(seat);return json({version:VERSION,result:await commit("attack_condition_failed",{seat,attack:atk.name,randoms})})}}if(cq.control==="Stunned")return json({ok:false,version:VERSION,error:"stunned_cannot_attack"},400);if(cq.control==="Dazed"){const r=coin();randoms.push({condition:"Dazed",result:r});cq.control=null;if(r==="tails"){directDamage(p.vanguard,30);log(`Dazed dealt 30 to Seat ${seat}'s Vanguard and ended the attack.`);const n=scanDefeats();if(n>0){s.phase="resolution";s.resume_after_resolution="aftermath"}else aftermath(seat);return json({version:VERSION,result:await commit("attack_condition_failed",{seat,attack:atk.name,randoms})})}}
   const unsupported=(ad?.id==="astral-celestyr-dream-cartographer"&&slot===1)||ad?.id==="astral-nebulynx"||ad?.id==="grove-myceliarch";if(unsupported)return json({ok:false,version:VERSION,error:"attack_effect_requires_pending_choice_engine",card_id:ad.id,attack_slot:slot},400);
   let targetSeat=otherSeat,targetWhere="vanguard",targetIndex:number|null=null,target=opp.vanguard as Cr|null;if(ad?.id==="gale-skyrend"&&body.target_reserve_index!=null){const ri=Number(body.target_reserve_index);if(!Number.isInteger(ri)||ri<0||ri>3||!opp.reserve?.[ri])return json({ok:false,version:VERSION,error:"legal_opposing_reserve_target_required"},400);target=opp.reserve[ri];targetWhere="reserve";targetIndex=ri}if(!target)return json({ok:false,version:VERSION,error:"legal_attack_target_required"},400);
   if(cq.control==="Blinded"){const pool:any[]=[];for(const who of [1,2])for(const x of allCr(s.players[String(who)]))pool.push({seat:who,...x});if(pool.length){const a=new Uint32Array(1);crypto.getRandomValues(a);const pick=pool[a[0]%pool.length];targetSeat=pick.seat;targetWhere=pick.where;targetIndex=pick.index;target=pick.cr;randoms.push({condition:"Blinded",target_seat:targetSeat,target_where:targetWhere,target_index:targetIndex});cq.control=null}}
   let bonus=0,ef=atk.effect.toLowerCase();if(ef.includes("target is scorched")&&hasCondition(target,"Scorched"))bonus+=30;if(ef.includes("target is venomed")&&hasCondition(target,"Venomed"))bonus+=20;if(ef.includes("target is mindbound")&&hasCondition(target,"Mindbound"))bonus+=30;if((ef.includes("target has a condition")||ef.includes("vanguard has a condition"))&&hasCondition(target))bonus+=ef.includes("+30")?30:20;if(ef.includes("3 or more reserve")&&p.reserve.filter(Boolean).length>=3)bonus+=20;if(ef.includes("reserve is full")&&p.reserve.filter(Boolean).length===4&&ef.includes("+"))bonus+=20;if(ef.includes("5 or more cards in hand")&&opp.hand.length>=5)bonus+=20;if(ef.includes("has a relic")&&p.vanguard.relic)bonus+=20;if(ef.includes("played a device this turn")&&Number(flags.device_turn??-1)===Number(s.turn_seq||0))bonus+=20;if(ef.includes("4 or more essence")&&p.vanguard.essence.length>=4)bonus+=20;if(ef.includes("became vanguard this turn")&&Number(p.vanguard.became_vanguard_turn??-1)===Number(s.turn_seq||0))bonus+=20;if(ef.includes("looked at a reward card this match")&&p.match_flags?.looked_reward)bonus+=20;if(ef.includes("looked at your deck this turn")&&Number(flags.looked_deck_turn??-1)===Number(s.turn_seq||0))bonus+=20;if(ef.includes("friendly damaged creature")){bonus+=Math.min(40,allCr(p).filter(x=>Number(x.cr.damage||0)>0).length*10)}if(ef.includes("prevented damage this turn")&&Number(flags.prevented_damage_turn??-1)===Number(s.turn_seq||0))bonus+=20;if(ef.includes("essence is discarded from this creature during this turn")&&Number((p.vanguard.flags as any)?.essence_discarded_turn??-1)===Number(s.turn_seq||0))bonus+=20;
   const dmg=attackDamage(p.vanguard,target,s,atk.damage+bonus);log(`Seat ${seat}'s ${ad?.name||"Vanguard"} used ${atk.name} for ${dmg.dealt} damage (${dmg.blocked} Shield prevented).`);
   if(ef.match(/place (\d+) damage on this creature/)){const m=ef.match(/place (\d+) damage on this creature/)!;directDamage(p.vanguard,Number(m[1]))}const sm=ef.match(/gain (\d+) shield/);if(sm)addShield(p.vanguard,Number(sm[1]));if(ef.includes("this creature becomes scorched"))applyCondition(p.vanguard,"Scorched",s);if(ef.includes("becomes blinded"))applyCondition(target,"Blinded",s);if(ef.includes("becomes venomed"))applyCondition(target,"Venomed",s);if(ef.includes("becomes rooted"))applyCondition(target,"Rooted",s);if(ef.includes("becomes silenced"))applyCondition(target,"Silenced",s);if(ef.includes("becomes mindbound"))applyCondition(target,"Mindbound",s);if(ef.includes("becomes crushed"))applyCondition(target,"Crushed",s);if(ef.includes("becomes drenched")&&Number(p.vanguard.shield||0)>0)applyCondition(target,"Drenched",s);if(ef.includes("becomes stunned"))applyCondition(target,"Stunned",s);if(ef.includes("heal 10 from this creature"))heal(p.vanguard,10);if(ef.includes("if this creature has shield, heal 20 from it")&&Number(p.vanguard.shield||0)>0)heal(p.vanguard,20);if(ef.includes("heal 20 from each friendly reserve creature")&&p.reserve.filter(Boolean).length===4)for(const cr of p.reserve)if(cr)heal(cr,20);if(ef.includes("top 2 cards of the opponent's deck")&&hasCondition(target)){for(let i=0;i<2&&opp.deck.length;i++)opp.discard.push(opp.deck.shift())}if(ad?.id==="astral-cosmarch"&&opp&&p.deck.length){const td=def(s,p.deck[0]);if(td?.element==="Astral"){p.hand.push(p.deck.shift());flags.looked_deck_turn=Number(s.turn_seq||0)}}
   if(ad?.id==="tide-tideroar"&&ef.includes("heal 30 from one friendly creature")){const where=String(body.heal_where||""),idx=body.heal_index==null?null:Number(body.heal_index),h=getCr(p,where,idx);if(!h)return json({ok:false,version:VERSION,error:"tideroar_heal_target_required"},400);heal(h,30)}
   if(ad?.id==="volt-stormmane"&&p.vanguard.essence.length>=4){const uid=String(body.discard_essence_uid||"");const k=p.vanguard.essence.findIndex((e:Inst)=>e.uid===uid);if(k<0)return json({ok:false,version:VERSION,error:"stormmane_attached_essence_discard_required"},400);p.discard.push(p.vanguard.essence.splice(k,1)[0]);p.vanguard.flags=p.vanguard.flags||{};(p.vanguard.flags as any).essence_discarded_turn=Number(s.turn_seq||0)}
   const wantsSwitch=ef.includes("switch this creature with a reserve creature")||ef.includes("move this creature to reserve after damage");if(wantsSwitch&&body.switch_reserve_index!=null)switchWithReserve(p,Number(body.switch_reserve_index),Number(s.turn_seq||0));if(ad?.id==="gale-aeralith-storm-shepherd"&&p.reserve.some(Boolean)&&body.switch_reserve_index==null)return json({ok:false,version:VERSION,error:"aeralith_switch_reserve_index_required"},400);
   const n=scanDefeats();if(n>0){s.phase="resolution";s.resume_after_resolution="aftermath"}else aftermath(seat);
   return json({version:VERSION,result:await commit("attack",{seat,attack_slot:slot,attack_name:atk.name,base_damage:atk.damage,bonus_damage:bonus,damage_dealt:dmg.dealt,shield_prevented:dmg.blocked,target_seat:targetSeat,target_where:targetWhere,target_index:targetIndex,randoms})});
  }

  return json({ok:false,version:VERSION,error:"unknown_action"},400);
 }catch(e){return json({ok:false,version:VERSION,error:e instanceof Error?e.message:String(e)},500)}
});