import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const VERSION="Code Labs Sol Guide V223";
const KEY=Deno.env.get("OPENAI_API_KEY")||"";
const MODEL=Deno.env.get("OPENAI_MODEL")||"gpt-5-mini";
const FALLBACK="gpt-5-mini";
const URL=Deno.env.get("SUPABASE_URL")||"";
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||"";
const ORIGINS=new Set(["https://chatterfriendsstreambandit.co.uk","https://www.chatterfriendsstreambandit.co.uk"]);
function cut(v:unknown,n:number){return String(v==null?"":v).slice(0,n)}
function headers(req:Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ORIGINS.has(o)?o:"https://chatterfriendsstreambandit.co.uk","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(req)})}
function page(v:unknown){const p=v&&typeof v==="object"?v as Record<string,unknown>:{};return{page:cut(p.page,300),title:cut(p.title,500),url:cut(p.url,2000),headings:Array.isArray(p.headings)?p.headings.slice(0,24).map(x=>cut(x,300)):[],visible_text:cut(p.visible_text,12000),button_labels:Array.isArray(p.button_labels)?p.button_labels.slice(0,40).map(x=>cut(x,200)):[],links:Array.isArray(p.links)?p.links.slice(0,40):[]}}
async function owner(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.toLowerCase().startsWith("bearer "))throw new Error("Sign in to Code Labs first.");if(!URL||!ANON)throw new Error("Code Labs authentication is not configured.");const sb=createClient(URL,ANON,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const u=await sb.auth.getUser();if(u.error||!u.data.user)throw new Error("Your Code Labs sign-in has expired.");const ok=await sb.from("code_labs_owners").select("user_id").eq("user_id",u.data.user.id).maybeSingle();if(ok.error||!ok.data)throw new Error("This account is not approved for Code Labs.")}
function answer(r:Record<string,unknown>){if(typeof r.output_text==="string")return r.output_text;const out=Array.isArray(r.output)?r.output as Array<Record<string,unknown>>:[],parts:string[]=[];for(const item of out){if(item.type!=="message"||!Array.isArray(item.content))continue;for(const p of item.content as Array<Record<string,unknown>>)if(p.type==="output_text"&&typeof p.text==="string")parts.push(p.text)}return parts.join("\n").trim()}
type Fail={status:number;code:string;message:string;model:string};
function modelFail(f:Fail){return f.status===400||f.status===404||/model|not_found|unsupported/i.test(f.code+" "+f.message)}
function safeError(f:Fail){if(f.status===401||f.status===403)return"Sol's server connection needs attention.";if(f.status===429)return"Sol is busy right now. Please wait a moment and try again.";if(f.status>=500)return"Sol's AI service is temporarily unavailable. Please try again shortly.";if(modelFail(f))return"Sol's configured AI model is unavailable. The safe fallback also could not respond.";return"Sol could not complete this guide request. Please start a new chat and try once more."}
async function call(request:Record<string,unknown>,model:string){const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({...request,model})});const data=await res.json().catch(()=>({})) as Record<string,unknown>;if(res.ok)return{ok:true as const,data,model};const e=data.error&&typeof data.error==="object"?data.error as Record<string,unknown>:{};const fail:Fail={status:res.status,code:cut(e.code||e.type||"upstream_error",120),message:cut(e.message||"Request failed",500),model};console.error("Sol guide upstream failure",{status:fail.status,code:fail.code,model});return{ok:false as const,fail}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:headers(req)});if(req.method!=="POST")return json(req,{ok:false,error:"POST required"},405);try{await owner(req);const body=await req.json().catch(()=>({})) as Record<string,unknown>;if(cut(body.action,40)==="health")return json(req,{ok:true,version:VERSION,configured:Boolean(KEY),model:MODEL,fallback_model:FALLBACK});if(!KEY)return json(req,{ok:false,error:"Sol needs server setup before it can answer."});const message=cut(body.message,12000).trim();if(!message)return json(req,{ok:false,error:"Message required"});const request:Record<string,unknown>={instructions:["You are Sol, the read-only page guide inside Code Labs for a non-coder.","Explain this page simply and suggest the next safe workflow step.","You have no tools and cannot change pages, repositories, deployments, data or settings.","Do not request or reveal credentials or hidden reasoning.","Describe required actions without pretending they happened."].join("\n"),input:JSON.stringify({current_page:page(body.page),recent_chat:Array.isArray(body.history)?body.history.slice(-10):[],user_request:message}),max_output_tokens:1800,store:true};const previous=cut(body.previous_response_id,160);if(previous)request.previous_response_id=previous;let result=await call(request,MODEL),used=false;if(!result.ok&&MODEL!==FALLBACK&&modelFail(result.fail)){used=true;result=await call(request,FALLBACK)}if(!result.ok)return json(req,{ok:false,error:safeError(result.fail),version:VERSION,category:result.fail.code});const text=answer(result.data);if(!text)return json(req,{ok:false,error:"Sol returned no guidance. Please start a new chat and try again.",version:VERSION});return json(req,{ok:true,version:VERSION,model:result.model,used_fallback:used,response_id:cut(result.data.id,160),text})}catch(error){const message=cut((error as Error).message||error,500),status=/sign in|expired|approved|authentication/i.test(message)?401:200;return json(req,{ok:false,error:message||"Sol guide is unavailable.",version:VERSION},status)}});
