import { activeSession, Binding, CLAIM, rest } from "./oauth.ts";
import { VERSION } from "./context.ts";
type Row=Record<string,any>;
function safe(value:unknown,max=350000){const text=JSON.stringify(value||{});if(text.length>max)throw new Error("Payload is too large.");return JSON.parse(text);}
async function current(b:Binding){const live=await activeSession(b.owner_id);return live.session as Row;}
export async function readPage(b:Binding){const s=await current(b);return{ok:true,version:VERSION,tool:"read_live_code_labs_page",session_id:s.id,page:s.page_name,page_url:s.page_url,page_fingerprint:s.page_fingerprint,last_seen_at:s.last_seen_at,page_snapshot:s.page_snapshot,last_receipt:s.last_receipt};}
async function enqueue(b:Binding,command:Row,risk=false){const s=await current(b);const expected=String(command.expected_page_fingerprint||"");if(!expected||expected!==String(s.page_fingerprint||""))throw new Error("Read the current live page first and use its exact page fingerprint.");const rows=await rest("code_labs_browser_commands",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({session_id:s.id,requested_by:CLAIM,command:safe(command),dangerous:risk})});return{ok:true,version:VERSION,command_id:rows[0].id,status:rows[0].status,page:s.page_name,page_fingerprint:s.page_fingerprint};}
export async function writeFields(b:Binding,args:Row){const fields=safe(args.fields||{},300000);const keys=Object.keys(fields);if(!keys.length||keys.length>100)throw new Error("Provide between 1 and 100 field writes.");return await enqueue(b,{type:"write_fields",expected_page_fingerprint:String(args.expected_page_fingerprint||""),fields});}
export async function writeSection(b:Binding,args:Row){const section=String(args.section_key||"").slice(0,180);if(!section)throw new Error("section_key is required.");return await enqueue(b,{type:"write_section",expected_page_fingerprint:String(args.expected_page_fingerprint||""),section,fields:safe(args.fields||{},300000)});}
export async function runAction(b:Binding,args:Row){const action=String(args.action_key||"").slice(0,220);if(!action)throw new Error("action_key is required.");const risk=/(delete|remove|trash|merge|publish|deploy|send|submit|approve|reject|production|main branch)/i.test(action);if(risk&&!(args.confirmed===true&&args.allow_dangerous===true))throw new Error("This action requires confirmed=true and allow_dangerous=true.");return await enqueue(b,{type:"run_action",expected_page_fingerprint:String(args.expected_page_fingerprint||""),action,confirmed:args.confirmed===true,allow_dangerous:args.allow_dangerous===true},risk);}
export async function undo(b:Binding,args:Row){return await enqueue(b,{type:"undo",expected_page_fingerprint:String(args.expected_page_fingerprint||"")});}
export async function receipt(b:Binding,args:Row){const s=await current(b);const id=String(args.command_id||"");if(!id)return{ok:true,version:VERSION,tool:"read_live_code_labs_receipt",session_id:s.id,receipt:s.last_receipt};const rows=await rest("code_labs_browser_commands?select=*&id=eq."+encodeURIComponent(id)+"&session_id=eq."+encodeURIComponent(s.id)+"&limit=1");if(!rows[0])throw new Error("Command receipt not found.");return{ok:true,version:VERSION,command_id:id,status:rows[0].status,receipt:rows[0].receipt,error:rows[0].error};}
