import { APPROVAL_PAGE, BASE, SCOPE, approve, authorize, binding, register, token } from "./oauth.ts";
import { VERSION, getContext, readUrl, saveRequest } from "./context.ts";
import { readPage, receipt, runAction, undo, writeFields, writeSection } from "./live.ts";
type Row=Record<string,any>;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body,null,2),{status,headers:{...cors,...extra,"Content-Type":"application/json","Cache-Control":"no-store"}});
const go=(url:string)=>new Response(null,{status:302,headers:{...cors,Location:url,"Cache-Control":"no-store"}});
const rpc=(id:unknown,result:unknown)=>json({jsonrpc:"2.0",id:id??null,result});
const rpcError=(id:unknown,code:number,message:string,status=400)=>json({jsonrpc:"2.0",id:id??null,error:{code,message}},status);
const protectedResource=()=>({resource:BASE,authorization_servers:[BASE],bearer_methods_supported:["header"],scopes_supported:["code_labs.read","code_labs.write"]});
const metadata=()=>({issuer:BASE,authorization_endpoint:BASE+"/oauth/authorize",token_endpoint:BASE+"/oauth/token",registration_endpoint:BASE+"/oauth/register",response_types_supported:["code"],response_modes_supported:["query"],grant_types_supported:["authorization_code","refresh_token"],token_endpoint_auth_methods_supported:["none"],code_challenge_methods_supported:["S256"],scopes_supported:["code_labs.read","code_labs.write"]});
function tools(){const fp={type:"string",description:"Exact page fingerprint from read_live_code_labs_page."};return[
{name:"get_code_labs_context",title:"Get Code Labs Context",description:"Read saved Code Labs context.",inputSchema:{type:"object",properties:{limit:{type:"number",minimum:1,maximum:25}}},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true}},
{name:"read_code_labs_url",title:"Read Code Labs URL",description:"Read a public Code Labs URL.",inputSchema:{type:"object",properties:{url:{type:"string"},max_chars:{type:"number",maximum:60000}},required:["url"]},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true}},
{name:"read_live_code_labs_page",title:"Read Live Code Labs Page",description:"Read the exact approved signed-in Code Labs page.",inputSchema:{type:"object",properties:{}},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true}},
{name:"write_live_code_labs_fields",title:"Write Live Code Labs Fields",description:"Write the smallest safe field set on the exact approved page.",inputSchema:{type:"object",properties:{expected_page_fingerprint:fp,fields:{type:"object",additionalProperties:true}},required:["expected_page_fingerprint","fields"]},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false}},
{name:"write_live_code_labs_section",title:"Write Live Code Labs Section",description:"Write safe fields in one page section.",inputSchema:{type:"object",properties:{expected_page_fingerprint:fp,section_key:{type:"string"},fields:{type:"object",additionalProperties:true}},required:["expected_page_fingerprint","section_key","fields"]},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false}},
{name:"run_live_code_labs_action",title:"Run Live Code Labs Action",description:"Press an approved page button by stable action key.",inputSchema:{type:"object",properties:{expected_page_fingerprint:fp,action_key:{type:"string"},confirmed:{type:"boolean"},allow_dangerous:{type:"boolean"}},required:["expected_page_fingerprint","action_key"]},annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:false}},
{name:"read_live_code_labs_receipt",title:"Read Live Code Labs Receipt",description:"Read a command result or latest page receipt.",inputSchema:{type:"object",properties:{command_id:{type:"string"}}},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true}},
{name:"undo_live_code_labs_write",title:"Undo Live Code Labs Write",description:"Undo the most recent page-field write.",inputSchema:{type:"object",properties:{expected_page_fingerprint:fp},required:["expected_page_fingerprint"]},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false}},
{name:"save_code_labs_write_request",title:"Save Code Labs Write Request",description:"Queue one branch and pull-request full-file request.",inputSchema:{type:"object",properties:{repo:{type:"string"},path:{type:"string"},branch:{type:"string"},content:{type:"string"},action:{type:"string"},commit_message:{type:"string"},pr_title:{type:"string"},pr_body:{type:"string"},confirm_branch_pr_only:{type:"boolean"}},required:["repo","path","branch","content","commit_message","pr_title","confirm_branch_pr_only"]},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false}}
];}
async function call(b:any,name:string,args:Row){if(name==="get_code_labs_context")return getContext(args.limit);if(name==="read_code_labs_url")return readUrl(args);if(name==="read_live_code_labs_page")return readPage(b);if(name==="write_live_code_labs_fields")return writeFields(b,args);if(name==="write_live_code_labs_section")return writeSection(b,args);if(name==="run_live_code_labs_action")return runAction(b,args);if(name==="read_live_code_labs_receipt")return receipt(b,args);if(name==="undo_live_code_labs_write")return undo(b,args);if(name==="save_code_labs_write_request")return saveRequest(args);throw new Error("Unknown tool.");}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const p=new URL(req.url).pathname;try{
if(p.endsWith("/.well-known/oauth-authorization-server")||p.endsWith("/.well-known/openid-configuration"))return json(metadata());
if(p.endsWith("/.well-known/oauth-protected-resource"))return json(protectedResource());
if(p.endsWith("/oauth/register")&&req.method==="POST")return json(await register(req),201);
if(p.endsWith("/oauth/authorize"))return go(await authorize(req));
if(p.endsWith("/oauth/approve")&&req.method==="POST")return json(await approve(req));
if(p.endsWith("/oauth/token")&&req.method==="POST")return json(await token(req));
if(req.method!=="POST")return json({ok:true,version:VERSION,approval_page:APPROVAL_PAGE,scope:SCOPE,tools:tools(),endpoint:BASE});
const body=await req.json().catch(()=>({})),id=body.id??null;
if(body.jsonrpc==="2.0"){
if(body.method==="initialize")return rpc(id,{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"code-labs-mcp-stub",version:VERSION},instructions:"Approve the exact signed-in Code Labs page, read it first, use the exact fingerprint, inspect the receipt, and keep GitHub changes branch and pull-request only."});
if(body.method==="ping")return rpc(id,{});if(body.method==="notifications/initialized")return new Response(null,{status:202,headers:cors});if(body.method==="tools/list")return rpc(id,{tools:tools()});if(body.method==="resources/list")return rpc(id,{resources:[]});if(body.method==="prompts/list")return rpc(id,{prompts:[]});
if(body.method==="tools/call"){const b=await binding(req);const result=await call(b,body.params?.name||"",body.params?.arguments||{});return rpc(id,{content:[{type:"text",text:JSON.stringify(result,null,2)}],structuredContent:result,isError:false});}return rpcError(id,-32601,"Unknown method",404);}
const b=await binding(req);return json(await call(b,body.tool||body.name||"",body));
}catch(e){const message=e instanceof Error?e.message:String(e);const status=/Missing bearer token|OAuth token|sign-in/i.test(message)?401:400;return json({ok:false,version:VERSION,error:message,wrote_database:false,wrote_github:false,opened_pr:false,deleted_anything:false},status,status===401?{"WWW-Authenticate":`Bearer resource_metadata="${BASE}/.well-known/oauth-protected-resource"`}:{});}});
