import { runtimeV02ApplyEffectDamagePacket, runtimeV02PreflightBeforeDamagePacket } from "./tcg-match-damage-packet-v0-2.ts";
import { runtimeV02DamageProtectionCount, runtimeV02InstallDamageProtection } from "./tcg-match-damage-protection-v0-2.ts";

function equal(actual:unknown, expected:unknown, label='mismatch'){if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(`${label}: ${JSON.stringify(actual)} != ${JSON.stringify(expected)}`)}
const inst=(uid:string)=>({uid,card_id:uid});
function fixture(){const target:any={stack:[inst('target')],essence:[],relic:null,damage:10,shield:10,flags:{}};const source:any={stack:[inst('source')],essence:[],relic:null,damage:0,shield:0,flags:{}};const state:any={turn_seq:6,active_seat:2,effect_events:[],players:{'1':{vanguard:target,reserve:[null,null,null,null]},'2':{vanguard:source,reserve:[null,null,null,null]}}};const lookup=()=>({});runtimeV02InstallDamageProtection(target,{protection_id:'veil:p1',source_action_id:'ability:veil',source_uid:'veil-source',source_card_id:'veil-card',source_kind:'ability',source_controller_seat:1,target_controller_seat:1,target_creature_uid:'target',installed_turn_seq:5,damage_classes:['effect'],source_controller:'opponent',reduce_amount:30,minimum:0,max_uses:1,expires_on:'start_of_controller_next_turn'});const context:any={packet_id:'effect-1',damage_class:'effect',condition:null,source_controller_seat:2,source_kind:'ability',source_action_id:'opp-effect',source_card_uid:'source',source_card_id:'source',source_creature_uid:'source',target_controller_seat:1,target_creature_uid:'target',target_zone:'vanguard',target_index:null};return{state,target,lookup,context}}

Deno.test('Damage #20 packet facade applies temporary effect protection before Shield and HP',()=>{const {state,target,lookup,context}=fixture();const r=runtimeV02ApplyEffectDamagePacket(state,target,50,context,lookup);equal(r.requested_amount,50);equal(r.final_amount,20);equal(r.receipt.shield_prevented,10);equal(r.receipt.actual_hp_damage,10);equal(target.damage,20);equal(target.shield,0);equal(runtimeV02DamageProtectionCount(target),0);equal(r.modifications[0].source_uid,'veil-source')});
Deno.test('Damage #20 packet preflight never consumes real temporary protection',()=>{const {state,target,lookup,context}=fixture();const r=runtimeV02PreflightBeforeDamagePacket(state,50,context,lookup);equal(r.final_amount,20);equal(runtimeV02DamageProtectionCount(target),1)});
