-- Stream Bandit replay foundation part.
-- SOURCE CANDIDATE ONLY.
-- Schema-only reconstruction of the pre-ledger foundation.
-- Test on a fresh database before any deployment or production decision.
-- Creates no rows and performs no destructive table or schema operation.

begin;

do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_posts_author_id_fkey' and conrelid='public.sb_social_posts'::regclass) then alter table public.sb_social_posts add constraint sb_social_posts_author_id_fkey foreign key (author_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_posts_target_profile_id_fkey' and conrelid='public.sb_social_posts'::regclass) then alter table public.sb_social_posts add constraint sb_social_posts_target_profile_id_fkey foreign key (target_profile_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_posts_group_id_fkey' and conrelid='public.sb_social_posts'::regclass) then alter table public.sb_social_posts add constraint sb_social_posts_group_id_fkey foreign key (group_id) references public.sb_social_groups(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_post_comments_post_id_fkey' and conrelid='public.sb_social_post_comments'::regclass) then alter table public.sb_social_post_comments add constraint sb_social_post_comments_post_id_fkey foreign key (post_id) references public.sb_social_posts(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_post_comments_author_id_fkey' and conrelid='public.sb_social_post_comments'::regclass) then alter table public.sb_social_post_comments add constraint sb_social_post_comments_author_id_fkey foreign key (author_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_post_comments_parent_comment_id_fkey' and conrelid='public.sb_social_post_comments'::regclass) then alter table public.sb_social_post_comments add constraint sb_social_post_comments_parent_comment_id_fkey foreign key (parent_comment_id) references public.sb_social_post_comments(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_post_media_post_id_fkey' and conrelid='public.sb_social_post_media'::regclass) then alter table public.sb_social_post_media add constraint sb_social_post_media_post_id_fkey foreign key (post_id) references public.sb_social_posts(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_post_media_user_id_fkey' and conrelid='public.sb_social_post_media'::regclass) then alter table public.sb_social_post_media add constraint sb_social_post_media_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_notifications_user_id_fkey' and conrelid='public.sb_social_notifications'::regclass) then alter table public.sb_social_notifications add constraint sb_social_notifications_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_notifications_actor_id_fkey' and conrelid='public.sb_social_notifications'::regclass) then alter table public.sb_social_notifications add constraint sb_social_notifications_actor_id_fkey foreign key (actor_id) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_user_friends_requester_id_fkey' and conrelid='public.sb_user_friends'::regclass) then alter table public.sb_user_friends add constraint sb_user_friends_requester_id_fkey foreign key (requester_id) references auth.users(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_user_friends_addressee_id_fkey' and conrelid='public.sb_user_friends'::regclass) then alter table public.sb_user_friends add constraint sb_user_friends_addressee_id_fkey foreign key (addressee_id) references auth.users(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_profile_social_settings_user_id_fkey' and conrelid='public.sb_profile_social_settings'::regclass) then alter table public.sb_profile_social_settings add constraint sb_profile_social_settings_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_owners_user_id_fkey' and conrelid='public.code_labs_owners'::regclass) then alter table public.code_labs_owners add constraint code_labs_owners_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_files_project_id_fkey' and conrelid='public.code_labs_files'::regclass) then alter table public.code_labs_files add constraint code_labs_files_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_jobs_project_id_fkey' and conrelid='public.code_labs_jobs'::regclass) then alter table public.code_labs_jobs add constraint code_labs_jobs_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_jobs_file_id_fkey' and conrelid='public.code_labs_jobs'::regclass) then alter table public.code_labs_jobs add constraint code_labs_jobs_file_id_fkey foreign key (file_id) references public.code_labs_files(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_packets_project_id_fkey' and conrelid='public.code_labs_packets'::regclass) then alter table public.code_labs_packets add constraint code_labs_packets_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_packets_job_id_fkey' and conrelid='public.code_labs_packets'::regclass) then alter table public.code_labs_packets add constraint code_labs_packets_job_id_fkey foreign key (job_id) references public.code_labs_jobs(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_test_runs_project_id_fkey' and conrelid='public.code_labs_test_runs'::regclass) then alter table public.code_labs_test_runs add constraint code_labs_test_runs_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_test_runs_job_id_fkey' and conrelid='public.code_labs_test_runs'::regclass) then alter table public.code_labs_test_runs add constraint code_labs_test_runs_job_id_fkey foreign key (job_id) references public.code_labs_jobs(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_versions_project_id_fkey' and conrelid='public.code_labs_versions'::regclass) then alter table public.code_labs_versions add constraint code_labs_versions_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_versions_job_id_fkey' and conrelid='public.code_labs_versions'::regclass) then alter table public.code_labs_versions add constraint code_labs_versions_job_id_fkey foreign key (job_id) references public.code_labs_jobs(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_versions_file_id_fkey' and conrelid='public.code_labs_versions'::regclass) then alter table public.code_labs_versions add constraint code_labs_versions_file_id_fkey foreign key (file_id) references public.code_labs_files(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_audit_log_project_id_fkey' and conrelid='public.code_labs_audit_log'::regclass) then alter table public.code_labs_audit_log add constraint code_labs_audit_log_project_id_fkey foreign key (project_id) references public.code_labs_projects(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='code_labs_audit_log_job_id_fkey' and conrelid='public.code_labs_audit_log'::regclass) then alter table public.code_labs_audit_log add constraint code_labs_audit_log_job_id_fkey foreign key (job_id) references public.code_labs_jobs(id) on delete cascade; end if; end $baseline$;

commit;
