-- Stream Bandit replay foundation part.
-- SOURCE CANDIDATE ONLY.
-- Schema-only reconstruction of the pre-ledger foundation.
-- Test on a fresh database before any deployment or production decision.
-- Creates no rows and performs no destructive table or schema operation.

begin;

-- Base tables are complete in parts 00-03. Referential contracts follow.
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_profiles_id_fkey' and conrelid='public.sb_profiles'::regclass) then alter table public.sb_profiles add constraint sb_profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_channels_owner_id_fkey' and conrelid='public.sb_channels'::regclass) then alter table public.sb_channels add constraint sb_channels_owner_id_fkey foreign key (owner_id) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_movies_channel_id_fkey' and conrelid='public.sb_movies'::regclass) then alter table public.sb_movies add constraint sb_movies_channel_id_fkey foreign key (channel_id) references public.sb_channels(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_movies_owner_id_fkey' and conrelid='public.sb_movies'::regclass) then alter table public.sb_movies add constraint sb_movies_owner_id_fkey foreign key (owner_id) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_collections_created_by_fkey' and conrelid='public.sb_collections'::regclass) then alter table public.sb_collections add constraint sb_collections_created_by_fkey foreign key (created_by) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_collection_movies_collection_id_fkey' and conrelid='public.sb_collection_movies'::regclass) then alter table public.sb_collection_movies add constraint sb_collection_movies_collection_id_fkey foreign key (collection_id) references public.sb_collections(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_collection_movies_movie_id_fkey' and conrelid='public.sb_collection_movies'::regclass) then alter table public.sb_collection_movies add constraint sb_collection_movies_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_playlists_owner_id_fkey' and conrelid='public.sb_playlists'::regclass) then alter table public.sb_playlists add constraint sb_playlists_owner_id_fkey foreign key (owner_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_playlist_movies_playlist_id_fkey' and conrelid='public.sb_playlist_movies'::regclass) then alter table public.sb_playlist_movies add constraint sb_playlist_movies_playlist_id_fkey foreign key (playlist_id) references public.sb_playlists(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_playlist_movies_movie_id_fkey' and conrelid='public.sb_playlist_movies'::regclass) then alter table public.sb_playlist_movies add constraint sb_playlist_movies_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_favourites_user_id_fkey' and conrelid='public.sb_favourites'::regclass) then alter table public.sb_favourites add constraint sb_favourites_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_favourites_movie_id_fkey' and conrelid='public.sb_favourites'::regclass) then alter table public.sb_favourites add constraint sb_favourites_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_likes_user_id_fkey' and conrelid='public.sb_likes'::regclass) then alter table public.sb_likes add constraint sb_likes_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_likes_movie_id_fkey' and conrelid='public.sb_likes'::regclass) then alter table public.sb_likes add constraint sb_likes_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_watch_progress_user_id_fkey' and conrelid='public.sb_watch_progress'::regclass) then alter table public.sb_watch_progress add constraint sb_watch_progress_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_watch_progress_movie_id_fkey' and conrelid='public.sb_watch_progress'::regclass) then alter table public.sb_watch_progress add constraint sb_watch_progress_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_watchlist_user_id_fkey' and conrelid='public.sb_watchlist'::regclass) then alter table public.sb_watchlist add constraint sb_watchlist_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_watchlist_movie_id_fkey' and conrelid='public.sb_watchlist'::regclass) then alter table public.sb_watchlist add constraint sb_watchlist_movie_id_fkey foreign key (movie_id) references public.sb_movies(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_genres_created_by_fkey' and conrelid='public.sb_genres'::regclass) then alter table public.sb_genres add constraint sb_genres_created_by_fkey foreign key (created_by) references auth.users(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_import_batches_imported_by_fkey' and conrelid='public.sb_import_batches'::regclass) then alter table public.sb_import_batches add constraint sb_import_batches_imported_by_fkey foreign key (imported_by) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_form_submissions_submitter_id_fkey' and conrelid='public.sb_form_submissions'::regclass) then alter table public.sb_form_submissions add constraint sb_form_submissions_submitter_id_fkey foreign key (submitter_id) references auth.users(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_submissions_submitter_id_fkey' and conrelid='public.sb_submissions'::regclass) then alter table public.sb_submissions add constraint sb_submissions_submitter_id_fkey foreign key (submitter_id) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_submissions_reviewed_by_fkey' and conrelid='public.sb_submissions'::regclass) then alter table public.sb_submissions add constraint sb_submissions_reviewed_by_fkey foreign key (reviewed_by) references public.sb_profiles(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_policy_documents_updated_by_fkey' and conrelid='public.sb_policy_documents'::regclass) then alter table public.sb_policy_documents add constraint sb_policy_documents_updated_by_fkey foreign key (updated_by) references auth.users(id) on delete set null; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_groups_owner_id_fkey' and conrelid='public.sb_social_groups'::regclass) then alter table public.sb_social_groups add constraint sb_social_groups_owner_id_fkey foreign key (owner_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_group_members_group_id_fkey' and conrelid='public.sb_social_group_members'::regclass) then alter table public.sb_social_group_members add constraint sb_social_group_members_group_id_fkey foreign key (group_id) references public.sb_social_groups(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_group_members_user_id_fkey' and conrelid='public.sb_social_group_members'::regclass) then alter table public.sb_social_group_members add constraint sb_social_group_members_user_id_fkey foreign key (user_id) references public.sb_profiles(id) on delete cascade; end if; end $baseline$;
do $baseline$ begin if not exists (select 1 from pg_constraint where conname='sb_social_group_members_invited_by_fkey' and conrelid='public.sb_social_group_members'::regclass) then alter table public.sb_social_group_members add constraint sb_social_group_members_invited_by_fkey foreign key (invited_by) references public.sb_profiles(id) on delete set null; end if; end $baseline$;

commit;
